### ISSUE TITLE
Unable to pull images from helm charts

### ISSUE THREAD

**Issue by windowsrefund** [k8s-at-home/charts#1019]
First saw this error when attempting to install the latest jackett chart. Now I'm seeing the same behavior with transmission which is interesting as this chart isn't using the recently refactored common chart. 

15s         Warning   Failed                   pod/transmission-65c649b46b-bxtx7           Failed to pull image "ghcr.io/k8s-at-home/transmission:v3.00": rpc error: code = Unknown desc = failed to pull and unpack image "ghcr.io/k8s-at-home/transmission:v3.00": failed to copy: httpReaderSeeker: failed open: failed to do request: Get "https://ghcr.io/v2/k8s-at-home/transmission/manifests/sha256:0dc1d9c53a2831fe9af69e55a1950fa5bed70a2ee7d01b2d7e554819082416b8": dial tcp 140.82.112.33:443: connect: network is unreachable

**Comment by onedr0p** [comment]
This seems like it could be a solar flare from GHCR, or something wrong with your CNI.

It pulls fine for me:

```
❯ docker pull ghcr.io/k8s-at-home/transmission:v3.00
v3.00: Pulling from k8s-at-home/transmission
345e3491a907: Already exists
57671312ef6f: Already exists
5e9250ddb7d0: Already exists
5cd78728eca3: Already exists
d7cb4155da3d: Already exists
3d5fe9c4e66a: Already exists
806a95a4d16e: Already exists
20026ece4b1a: Pull complete
57ef9789af27: Pull complete
ab8f6a334664: Pull complete
35d74be4f1fe: Pull complete
6097237b06eb: Pull complete
80307bd25347: Pull complete
Digest: sha256:0dc1d9c53a2831fe9af69e55a1950fa5bed70a2ee7d01b2d7e554819082416b8
Status: Downloaded newer image for ghcr.io/k8s-at-home/transmission:v3.00
ghcr.io/k8s-at-home/transmission:v3.00
```

**Comment by windowsrefund** [comment]
Yes, I pulled fine outside of the helm chart before I filed this issue. I've also installed several other charts (longhorn, and even halkweye/jackett) so I can't see how it would be on my end. Given all the heavy lifting going on over there, I thought I'd share what I'm seeing. Can you install the helm chart?

**Comment by onedr0p** [comment]
I have the helm chart and images working fine in my cluster.

**Comment by windowsrefund** [comment]
OK. I'll keep digging on my end. Appreciate knowing things are looking good on your side.
