### ISSUE TITLE
[home-assistant] missing service account config

### ISSUE THREAD

**Issue by xeor** [k8s-at-home/charts#102]
The home-assistant chart (https://github.com/k8s-at-home/charts/tree/master/charts/home-assistant) is missing an option to define serviceAccount.

Many of the other charts have that, like https://github.com/k8s-at-home/charts/tree/master/charts/homebridge.

**Comment by onedr0p** [comment]
Hi @xeor please feel free to open a PR if you think is is useful to you.

Thanks!

**Comment by xeor** [comment]
yea, I was wondering if I should have done that :) However, I've moved on to another solution now, so if this is not that commonly used, I'll leave it for someone else to do the PR.

**Comment by bjw-s** [comment]
This will be fixed when #333 is merged, closing this one for now 🙂
