### ISSUE TITLE
[searx] update application version to >= 1.0.0

### ISSUE THREAD

**Issue by berlincount** [k8s-at-home/charts#1020]
# Details

**Helm chart name:**

searx

**Describe the solution you'd like:**

updated application version, variables and templates

it seems like too many things changed for a simple version bump to suffice :-/

**Anything else you would like to add:**

I'm too new to Helm myself to be of much use yet, sorry

**Additional Information:**

I love your project <3

**Comment by nicholaswilde** [comment]
This one is on our todo list #942 to upgrade charts to common v3. We'll close this issue for now.

**Comment by berlincount** [comment]
Please note that some variables etc seem to have been updated, so it's sadly not a simple version bump only (I tried)
