### ISSUE TITLE
[icinga2] application chart

### ISSUE THREAD

**Issue by berlincount** [k8s-at-home/charts#1022]
# Details

**Helm chart name:**

icinga2

**Describe the solution you'd like:**

there doesn't seem to be any kind of chart for the community version of https://icinga.com/ yet, but I'd love to use one!

**Anything else you would like to add:**

I'm too new to Helm myself to be of much use yet, sorry

**Additional Information:**

I love your project <3

**Comment by nicholaswilde** [comment]
Thanks for the request! 🙏🏽  Do you happen to know if a multi-architecture container exists for this application? If so, would you mind providing a link?

**Comment by nicholaswilde** [comment]
It looks like the [latest version](https://hub.docker.com/layers/jordan/icinga2/latest/images/sha256-40f4e40a497ba33558368400fa3d6d03ded7af5412768bd542b22ffc4ed2687c?context=explore) by jordan is multi-arch. Is this the image that you'd like the image to be based on?

**Comment by berlincount** [comment]
I'm honestly not sure - https://hub.docker.com/r/icinga/icinga2 seems more appropriate, but jordan's image seems quite popular, so I'd have a tendency to use that, even if it doesn't seem as regularily updated ... hm.

multi-arch is preferred, if not mandatory, correct?

**Comment by nicholaswilde** [comment]
> multi-arch is preferred, if not mandatory, correct?

It's mandatory to support `arm64` and `amd64`.
