### ISSUE TITLE
[Komga] application chart

### ISSUE THREAD

**Issue by Infray** [k8s-at-home/charts#1036]
# Details

Helm chart name:

Komga

Describe the solution you'd like:

I was looking for a comic media server but couldn't find one listed in your charts. This one seems to be up for the job. 

Anything else you would like to add:

General info I've found:
repo: https://github.com/gotson/komga
available container image: https://hub.docker.com/r/gotson/komga

Additional Information:

Great work guys!

**Comment by nicholaswilde** [comment]
Thanks for submitting this request. 🙏
 We will let you know if we have any questions.
