### ISSUE TITLE
[vaultwarden] external database

### ISSUE THREAD

**Issue by lcotonea** [k8s-at-home/charts#1053]
# Details

**Helm chart name:** vaultwarden

**Describe the solution you'd like:** External database
I use to have a single database service on my k8s cluster to facilitate configuration and maintenance. Moreover, I run my K8s on ARM. However, the vaultwarden chart doesn't offer a way to use an external database, and the bitnami database charts are not yet ARM ready (but vaultwarden is ARM ready). Then to make a strong dependance with bitnami databases causes a lost of ARM compatibility.
Is it possible to add an "externalDatabase" section like the previous bitwarden chart?

**Comment by bjw-s** [comment]
This is already possible. When you leave the `mariadb.enabled` and `postgresql.enabled` set to `false`, no database will be deployed along with the chart. 

You should then be able to configure Vaultwarden to use an existing database by specifying the desired environment variabled:
https://github.com/dani-garcia/vaultwarden/blob/main/.env.template#L10L21
