### ISSUE TITLE
Adguard-home - Liveness probe failed / Connection failed

### ISSUE THREAD

**Issue by mr-onion-2** [k8s-at-home/charts#107]
Hi

Apologies if this is not the right place to ask, since this is probably more due to my lack of experience with Helm rather than any issue with this chart.

I am running a clean k3s environment on a Pi4. Just the one node for now.

The only values I have overridden in the adguard-home chart are the image tag (armhf-latest) and the existingClaim. 

I can port-forward to the pod on port 3000 and access and complete the setup wizard at /install.html, but after this it says the connection was reset. Then eventually the liveness probe fails with e.g. _Get http://10.42.0.70:3000/login.html: dial tcp 10.42.0.70:3000: connect: connection refused_.

Am I missing something in my environment setup?

Environment:
Raspberry Pi4 
5.4.73-v8+ #1360 SMP PREEMPT Thu Oct 29 16:00:37 GMT 2020 aarch64 GNU/Linux
Running k3s version v1.18.9+k3s1 (630bebf9)

Many thanks

**Comment by dcplaya** [comment]
During the setup wizard, do you keep the port as `3000`? Or do you change it to something else?

Do you have an external IP setup for AdGuard?
Do you have ingress set up for it?

**Comment by mr-onion-2** [comment]
Good call - I had left it as port 80. Changing it to 3000 has done the trick - thanks!

Aside from that I hadn't enabled my configAsCode block so I shouldn't have had the wizard anyway.

It doesn't look like the 'subPath' is being used within the chart. I assumed this is meant to define a subpath within the persistent volume path? I can create a new issue for that if so.

Many thanks

**Comment by dcplaya** [comment]
The wizard runs if there is no current config, what you enter in the wizard is basically making the starting config, which should be almost identical to the `configAsCode`.  I worried about this exact problem when I made this chart but there was no way around it.

As for the port 53 issue,
You probably want to use your externalIP for the DNS lookups. I dont know your setup exactly but I use the externalIP.  One way to check is to look at the kube services for that namespace. `kubectl get svc -n NAMESPACE` You should see port 53 listed by the `adguard-home-tcp` and `adguard-home-upd` along with an IP.

**Comment by mr-onion-2** [comment]
Yeh I configured my configAsCode block from my old config file but I just hadn't noticed the 'enable' flag, which is what threw me off a bit. 

I'll have another play with the port 53 service bit and will close this issue for now as I think it's more likely something wrong in my overall set up. If I do pinpoint the issue I'll put a comment on for future reference.

Thanks again for your help and the great project.

**Comment by dcplaya** [comment]
Feel free to join the discord!  Might get quicker help or just come hangout
https://discord.gg/tfAZPvSS

**Comment by mr-onion-2** [comment]
Thanks, might just do that :)
