### ISSUE TITLE
Roll deployments on configmap changes

### ISSUE THREAD

**Issue by onedr0p** [k8s-at-home/charts#1095]
# Details

**Describe the solution you'd like:**

Roll deployments on configmap changes, see https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments

**Charts to implement this solution:**
- [ ] Blocky
- [ ] Mosquitto

**Comment by bjw-s** [comment]
I have transferred the issue to our Charts repo, since this is something we would need to implement here (the library has no knowledge of any configMaps/Secrets/etc required by the subCharts).

**Comment by bjw-s** [comment]
Additional reference links:
- https://blog.questionable.services/article/kubernetes-deployments-configmap-change/#example
- https://github.com/grafana/helm-charts/search?q=sha256sum&type=
