### ISSUE TITLE
node-red 1.3.5 old

### ISSUE THREAD

**Issue by brianmay** [k8s-at-home/charts#1127]
# Details

**Helm chart name and version:** node-red 9.0.0

Just wondering if there is any interest, known problems, etc, with updating the node-red chart to use upstream 2.0.5?

**Comment by onedr0p** [comment]
I've upgraded the image in my helm deployment just fine.

**Comment by brianmay** [comment]
But maybe the chart should be updated to use the new version of the image by default? That was my point.

**Comment by onedr0p** [comment]
When using our helm charts as we don't automate image updates to the helm charts.  We could easily have renovate manage deps in our charts and bump image versions but we aren't the developers of the applications. It's hard to test whether or not image updates will break helm charts and offload that to the user to debug. I hope that makes sense.

However, we definitely accept PRs to bump image versions.
