### ISSUE TITLE
searx: no searx-checker container

### ISSUE THREAD

**Issue by disconn3ct** [k8s-at-home/charts#1138]
# Details

**Helm chart name and version:**
searx 5.0.0

**Container name and tag:**
searx/searx-checker:latest

**What steps did you take and what happened:**
The container doesn't exist. https://hub.docker.com/r/searx/searx-checker is 404
It cannot be disabled in values.

**Relevant Helm values:**

**What did you expect to happen:**
`enabled:` variable and default images to exist

**Anything else you would like to add:**

**Additional Information:**

**Comment by bjw-s** [comment]
Should be fixed now that #1136 is merged. Please feel free to reopen if it isn't :)
