### ISSUE TITLE
speedtest-prometheus - 429 Too Many Requests

### ISSUE THREAD

**Issue by madAndroid** [k8s-at-home/charts#1150]
# Details

**Helm chart name and version:**

k8s-at-home/speedtest-prometheus -- 2.1.2

**Container name and tag:**

billimek/prometheus-speedtest-exporter:1.1.0

**What steps did you take and what happened:**

Speedtest exporter suddently stopped working 

**Relevant Helm values:**

defaults used

**What did you expect to happen:**

Speedtest to return data

**Anything else you would like to add:**

Running the script on the container:

```
bash-5.0# /usr/local/bin/speedtest-exporter.sh
[2021-09-01 11:24:20.246] [error] Limit reached:
<html>
<head><title>429 Too Many Requests</title></head>
<body>
<center><h1>429 Too Many Requests</h1></center>
<hr><center>openresty</center>
</body>
</html>
```

Do we need to set a limit on number of requests? I'm using Prom defaults (`scrape_interval: 1m`)

**Comment by onedr0p** [comment]
The default time it runs a speedtest is based on `prometheus.podMonitor.interval` which is defaulted to `1h`

**Comment by madAndroid** [comment]
This has been running fine like this for months and months now 😁 
I understand it might be that they've only now decided to rate limit connections from here ... but once an hour seems way too infrequent .. I may as not run it at all, if I'm only going to expect a result every hour - I will see if I can increase the interval to be every 20 minutes instead

**Comment by onedr0p** [comment]
I would also suggest opening any issue with the application over at https://github.com/MiguelNdeCarvalho/speedtest-exporter

**Comment by madAndroid** [comment]
@onedr0p  - thank you, I have created an issue there: https://github.com/MiguelNdeCarvalho/speedtest-exporter/issues/92
