### ISSUE TITLE
Traefik-Forward-Auth: Switch to different upstream image for 

### ISSUE THREAD

**Issue by h3mmy** [k8s-at-home/charts#1166]
# Details

**Helm chart name:**

Traefik Forward Auth

**Describe the solution you'd like:**

Consider switching upstream image from thomseddon/traefik-forward-auth to mesosphere/traefik-forward-auth. It's a spin off from the thomseddon image but is actively maintained as of right now. The key differences are outlined in the README (here)[https://github.com/mesosphere/traefik-forward-auth]

**Anything else you would like to add:**

I'm not affiliated with either repo. I've just been setting up forward auth in my personal space and discovered the thomseddon image isn't as maintained anymore and that's what I've used in the past. I ran into the mesosphere one and figured I would share that here since that's what I've decided to use and will probably have to make a Chart for it at some point.

**Additional Information:**

I'm primarily using this to have a discussion and/or to bring this to the attention of the Code Owners. Having an upstream project that's actively maintained seems like a good thing for maintenance here going forward. There would be some breaking changes but I feel like it should be considered, however I suppose one could split it off as a separate chart entirely.

**Comment by onedr0p** [comment]
I'm going to ask if you have time to help submit a PR, we're definitely open to this. We like supporting active projects too :)

**Comment by h3mmy** [comment]
I can certainly work on it. Will probably be able to start this weekend
