### ISSUE TITLE
[question] new "common" chart vs. "The Common Helm Helper Chart"

### ISSUE THREAD

**Issue by michaelkoetter** [k8s-at-home/charts#119]
Hi guys, just saw that there is a new `common` library chart that replaces `media-common`.

There's also something called [The Common Helm Helper Chart](https://github.com/helm/charts/blob/master/incubator/common/README.md) in the Helm incubator repository. Maybe this could be used and extended by the k8s-at-home chart? It could reduce the amount of code in k8s-at-home chart and at the same time ensure we follow Helm best practices.

There would be a name clash, so the k8s-at-home chart would need a new unique name (as `common` is already used by the The Common Helm Helper Chart).

**Comment by onedr0p** [comment]
@michaelkoetter with the help from @bjw-s and @DirtyCajunRice we decided to build our own. That repository will be archived and set to read-only within the coming days. We basically wanted our own `common` library that we can have control over.

**Comment by michaelkoetter** [comment]
Thanks for the clarification! I didn't see how outdated the Helm chart was, now this really looks like a stupid question ;)
