### ISSUE TITLE
Upgrade remaining charts to use new common chart

### ISSUE THREAD

**Issue by onedr0p** [k8s-at-home/charts#120]
- [x] jackett
- [x] sonarr
- [x] radarr
- [x] lidarr
- [x] bazarr
- [x] sabnzbd
- [x] nzbget
- [x] tautulli
- [x] organizr
- [x] ombi
- [x] qbittorrent
- [x] nzbhydra2

Closes https://github.com/k8s-at-home/charts/issues/106

**Comment by onedr0p** [comment]
Radarr done in https://github.com/k8s-at-home/charts/pull/121

**Comment by onedr0p** [comment]
Sonarr done in https://github.com/k8s-at-home/charts/pull/122

**Comment by onedr0p** [comment]
Lidarr done in https://github.com/k8s-at-home/charts/pull/123

**Comment by onedr0p** [comment]
Bazarr done in https://github.com/k8s-at-home/charts/pull/124

**Comment by onedr0p** [comment]
Sabnzbd done in https://github.com/k8s-at-home/charts/pull/125

**Comment by onedr0p** [comment]
Ombi done in https://github.com/k8s-at-home/charts/pull/126

**Comment by onedr0p** [comment]
Tautulli done in https://github.com/k8s-at-home/charts/pull/127

**Comment by onedr0p** [comment]
Nzbhydra2 done in https://github.com/k8s-at-home/charts/pull/128

**Comment by onedr0p** [comment]
Organizr done in https://github.com/k8s-at-home/charts/pull/129

**Comment by bjw-s** [comment]
Nzbget done in #131

**Comment by bjw-s** [comment]
Qbittorrent done in #132

**Comment by bjw-s** [comment]
Will go over the other ones to bump `common` to 1.0.5 later on to get the latest fixes, I think we can close this issue afterwards.

**Comment by bjw-s** [comment]
> Will go over the other ones to bump `common` to 1.0.5 later on to get the latest fixes, I think we can close this issue afterwards.
Bumps done in #133
