### ISSUE TITLE
New helm chart - wildduck

### ISSUE THREAD

**Issue by whit-colm** [k8s-at-home/charts#1218]
# Details

**Helm chart name:** `wildduck`

**Describe the solution you'd like:** [wildduck](https://github.com/nodemailer/wildduck) is an email server designed to be highly scalable, more modern email server, and as such could be extremely useful for a number of people. Would it be possible for someone to create a helm chart for it as the developer has stated they're not comfortable enough with k8s to do so themself.

**Comment by xavier83** [comment]
slightly unrelated, but there is another batteries included email server bundle [docker-mailserver](https://github.com/docker-mailserver/docker-mailserver) that could use a hosted chart repo https://github.com/docker-mailserver/docker-mailserver-helm/issues/44

**Comment by Berndinox** [comment]
Im also looking for an k8s chart.
Im kind of busy, but I will create one in the upcoming weeks _(hopefully not months)_

**Comment by angelnu** [comment]
As I am also affected by the free Google Apps going away I am getting the final motivation to move email/calendar to K8S. So I am also interested in consuming/contributing this. Will see if I can get moving this weekend.
