### ISSUE TITLE
[teslamate] Artifact Hub links do not point here.

### ISSUE THREAD

**Issue by stobias123** [k8s-at-home/charts#1244]
# Details

All of your artifact hub source code links direct to a different project. Your readme shows that this project is not related to the upstream project, yet you link to the upstream project. 

Please link to this repository in the artifact hub.

**Comment by bjw-s** [comment]
Not a problem at all :) We try to make it clear that we are not the maintainers of the underlying projects but given the amount of charts we now host, some may have slipped through the cracks :)

I've modified the title to indicate that this affects the TeslaMate chart, and we'll try to update it in an upcoming patch release.
