### ISSUE TITLE
[Vaultwarden] does not start without persistence enabled

### ISSUE THREAD

**Issue by lapwat** [k8s-at-home/charts#1262]
# Details

**Helm chart name and version:**

vaultwarden 3.1.3

**What steps did you take and what happened:**

helm install vaultwarden k8s-at-home/vaultwarden

**Relevant Helm values:**

persistence.config.enabled: false

**What did you expect to happen:**

I expect that vaultwarden starts with empty dir 'config' created inside the container.

**Anything else you would like to add:**

If I enable persistence, I expect my volumes not to be deleted  if I uninstall the helm chart.

**Logs**

```txt
[2021-11-01 11:13:28.573][vaultwarden][ERROR] Data folder 'config' doesn't exist.
[2021-11-01 11:13:28.573][vaultwarden][ERROR] Verify that your data volume is mounted at the correct location.
```

**Comment by bjw-s** [comment]
This is not the repo to post issues with specific charts. Moved the issue to our charts repository.

**Comment by bjw-s** [comment]
Vaultwarden requires a `/config` folder to be present. By default we do not specify this because there can be all sorts of ways that a user wishes to mount persistence on that mountpoint.

If you want to run the chart without providing actual persistence, you could set the following values:
```yaml
persistence:
  config:
    enabled: true
      type: emptyDir
```
