### ISSUE TITLE
Blocky: Unable to configure ingress with TLS for DoH

### ISSUE THREAD

**Issue by samip5** [k8s-at-home/charts#1279]
# Details

**Helm chart name and version:** Blocky 9.0.3

**Container name and tag:** Blocky v0.17

**What steps did you take and what happened:**

Chart has no way to do proper TLS ingress for Blocky due to it requiring the certificate and key in the container itself.

This was added recently:
https://github.com/0xERR0R/blocky/releases/tag/v0.17

**Comment by onedr0p** [comment]
Why can't the chart do ingress?

**Comment by samip5** [comment]
> Why can't the chart do ingress?

The Blocky instance requires the certificate to be at a specified path, so probably saying the chart can't do ingress is false. It can, but the certficate for the HTTPS/TLS ingress needs an certFile configuration parameter and that needs to be accessable by Blocky.

https://0xerr0r.github.io/blocky/configuration/

**Comment by onedr0p** [comment]
I'm still not following couldn't you mount that in as a volume and update the config?

**Comment by samip5** [comment]
Not sure how I would do that so that it would use the already existing certificate.

**Comment by onedr0p** [comment]
Seems like you'll need to do some engineering to make cert-manager work with blocky looking over blocky docs, this is what you want to do right? https://github.com/0xERR0R/blocky/wiki/Configuration-of-HTTPS-for-DoH-and-Rest-API

**Comment by samip5** [comment]
Pretty much yeah.

**Comment by samip5** [comment]
> Try this;
> 
> Create certificate using cert-manager. Name it something like `blocky-cert`
> 
> Update your blocky deployment using this chart with;
> 
> ```
> persistence:
>   blocky-cert:
>     enabled: true
>     mountPath: /cert
>     type: secret
>     name: blocky-cert
> ```
> 
> in the `config:` section add
> 
> ```
> httpPort: 4000
> httpsPort: 443
> tlsPort: 853
> certFile: /cert/tls.crt
> keyFile: /cert/tls.key
> ```
> 
> if you're using `stakater/reloader` you can add
> 
> ```
> podAnnotations:
>   secret.reloader.stakater.com/reload: blocky-cert
> ```
> 
> Full example in my repo here; https://github.com/mcfio/home-cluster/blob/main/cluster/apps/home/blocky/helm-release.yaml

That unfortunately just resulted in Blocky not booting up due to not finding the cert, despite it being a secret in the same namespace, and reloader didin't do anything about it...

**Comment by samip5** [comment]
Oh, it was due to a typo. Now it works. :)
