### ISSUE TITLE
Home-Assistant: Postgresql Nearing End of Support

### ISSUE THREAD

**Issue by carpenike** [k8s-at-home/charts#1297]
# Details

**Home Assistant:**
Per Home Assistant documentation, Postgres must be >= v12: https://www.home-assistant.io/blog/2021/11/03/release-202111/

```
Recorder / Databases

The Home Assistant project has now explicitly defined a set of databases that are supported by the recorder.

We now support the following databases:

    MariaDB ≥ 10.3
    MySQL ≥ 8.0
    PostgreSQL ≥ 12
    SQLite ≥ 3.32.1

All other databases and database versions are now deprecated.

```

Bitnami is tracking the v11 version and appears to be working on a v13 PR.

Per logs in hass container, recorder will no longer start with a non-supported version of Postgres starting with Home Assistant 2022.2.

**Comment by bjw-s** [comment]
It doesn't look like the referred issue is getting much traction. How would we best tackle this? 
We could specify a default "custom" image version for the postgresql chart dependency in our values.yaml? 

We should probably have renovate update those on a similar interval to the helm chart (every 1st of the month), to keep them up to date.
