### ISSUE TITLE
RFC: most charts should be StatefullSet, but are Deployments

### ISSUE THREAD

**Issue by ishioni** [k8s-at-home/charts#13]
I believe that charts which deploy stateful applications, like for example Home Assistant, radarr et all should deploy statefullsets instead of deployments. I know that one can get almost the same result using a chart hardcoded replica number, and deployment strategy so as to guard from 2 copies accessing the same file (like on a new version rollout) from a PVC. I also realise that most of these applications have no business of being deployed in more than one copy from the same deployment, since they don't cluster in any meaningful way.

Meanwhile statefullsets have these things built-in. They also have a neat optional bonus (or a hindrance, depending on ones usecase), that because they bring pvc templates instead of pvc, helm will not delete the pvc outright on uninstall.

This is not a critique, it's a call for comments: are people using deployments instead of statefullsets because of familiarity, or is there something i'm not seeing?

**Comment by ishioni** [comment]
@DirtyCajunRice 

Not sure if people would be on board with this, as it duplicates a lot of lines. But it is one way of tackling the problem

**Comment by onedr0p** [comment]
I am going to close this issue, with the [common](https://github.com/k8s-at-home/charts/tree/master/charts/common) library @bjw-s / @DirtyCajunRice put together solved this issue for the charts that use it. Meaning to say the user has an option to use a controller type of sts or deployment. Moving forward in new charts, it would be nice if more ppl got onboard using this library. Besides a few outliers most charts here follow the same type of pattern and can easily be made using that library.
