### ISSUE TITLE
[focalboard] Chart's default vaules causes pod to CrashBackOffLoop

### ISSUE THREAD

**Issue by PrymalInstynct** [k8s-at-home/charts#1303]
# Details

**Helm chart name and version:**
focalboard v4.1.0

**Container name and tag:**
mattermost/focalboard:0.11.0

**What steps did you take and what happened:**
Installed the helm chart to my cluster via Kustomization HelmRelease and the Pod goes into a CrashBackOffLoop

**Relevant Helm values:**
Changed no default values but the container image tag to 0.11.0 (most recent), and setup ingress/persistent storage

```
image:
  # -- image repository
  repository: mattermost/focalboard
  # -- image pull policy
  pullPolicy: IfNotPresent
  # -- image tag
  tag: 0.11.0

# -- environment variables.
# @default -- See below
env: {}

# See the Administrator's Guide for config reference: https://www.focalboard.com/guide/admin/
config: |
  {
    "serverRoot": "http://localhost:8000",
    "port": 8000,
    "dbtype": "sqlite3",
    "dbconfig": "/data/focalboard.db",
    "postgres_dbconfig": "dbname=focalboard sslmode=disable",
    "useSSL": false,
    "webpath": "./pack",
    "filespath": "/data/files",
    "telemetry": true,
    "session_expire_time": 2592000,
    "session_refresh_time": 18000,
    "localOnly": false,
    "enableLocalMode": true,
    "localModeSocketLocation": "/var/tmp/focalboard_local.socket"
  }

ingress:
  main:
    enabled: true
    ingressClassName: "traefik"
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-production"
      hajimari.io/enable: "true"
      hajimari.io/icon: "notebook-outline"
      traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      traefik.ingress.kubernetes.io/router.middlewares: "networking-basic-auth@kubernetescrd"
    hosts:
      - host: "focalboard.${SECRET_DOMAIN}"
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - "focalboard.${SECRET_DOMAIN}"
        secretName: focalboard-tls

persistence:
  data:
    enabled: true
    existingClaim: focalboard-data-v1
```

**What did you expect to happen:**
I expected the chart to install and the container to come up

**Anything else you would like to add:**
The Pod goes into a crashBackOffLoop with the following error from the pod logs

```
# kubectl logs -f focalboard-d75b98894-bpht6 -n productivity
2021/12/11 14:13:20 Unable to read the config file: 1 error(s) decoding:

* cannot parse 'port' as int: strconv.ParseInt: parsing "tcp://10.43.219.133:8000": invalid syntax
```

**Additional Information:**
It appears based on the error that something is overwriting the config "port' with tcp://10.43.219.133:8000 when it is set to 8000 in the helm-release

**Comment by bjw-s** [comment]
I have looked through the chart, but I cannot find anywhere in the chart where we change these settings. I am wondering if this is being caused by [Kubernetes service links](https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/#accessing-the-service). Those would create an environment variable called `FOCALBOARD_PORT`, and if the application can be configured through environment variables (maybe this is a recent change?) the application will fail to start.

Could you try to set `enableServiceLinks: true` to false in your values.yaml and see if it works then?

**Comment by PrymalInstynct** [comment]
I put `enableServiceLinks: false` under values in my helm-release.yaml file at the same indentation as image but got the same result.
