### ISSUE TITLE
Add support for revisionHistoryLimit for deployments

### ISSUE THREAD

**Issue by samip5** [k8s-at-home/charts#1363]
# Details

**Helm chart name:** All of them

**Describe the solution you'd like:** I would like to be able to set revisionHistoryLimit on the deployment.

**Comment by onedr0p** [comment]
Did you mean to open this PR in the library charts repo?

**Comment by samip5** [comment]
No because I'm not sure which it should be on as the charts here can have custom deployments.

**Comment by onedr0p** [comment]
This feature already exists and you can set it for anything you want, we don't want to maintain details. It should be up to you want you want this value to be

https://github.com/k8s-at-home/library-charts/search?q=revisionHistoryLimit&type=
