### ISSUE TITLE
Homebridge: Updated Container Image

### ISSUE THREAD

**Issue by Rahulsharma0810** [k8s-at-home/charts#1369]
# Details

**Helm chart name:**

Homebridge

**Describe the solution you'd like:**

The current container image is not updated, either the chart should use `oznu/homebridge:ubuntu` or there should be option to set a custom image.

**Anything else you would like to add:**

Also, the startup script doesn't work at all.

**Comment by Rahulsharma0810** [comment]
Do not stale

**Comment by bjw-s** [comment]
> or there should be option to set a custom image.

All of our charts allow setting a custom value for both `image.repository` and `image.tag`.

> Also, the startup script doesn't work at all.

Can you please elaborate on this?

**Comment by Rahulsharma0810** [comment]
I will check on image with `image.repository` and `image.tag`, 

In the startup script, I added some plugins and homebridge update command and it never updates/installs it. UI always show old version.

**Comment by bjw-s** [comment]
https://github.com/k8s-at-home/charts/pull/1534 Should fix the problem with the startup script.
Do note that the key in `values.yaml` has changed, so you will have to modify your configuration accordingly.
