### ISSUE TITLE
[rtorrent-flood] vpn support

### ISSUE THREAD

**Issue by jffz** [k8s-at-home/charts#139]
Is there any plan to add vpn support ?

**Comment by onedr0p** [comment]
@jffz we're always looking for help with contributing to this project. 

Right now we have a [qbittorrent container image](https://github.com/k8s-at-home/container-images) that works well with our [qbittorrent helm chart](https://github.com/k8s-at-home/charts/tree/master/charts/qbittorrent).

In fact any helm chart that uses the [common library](https://github.com/k8s-at-home/charts/tree/master/charts/common) and our [container images](https://github.com/k8s-at-home/container-images) inherits VPN support.
