### ISSUE TITLE
`./hack/gen-helm-docs.sh` broken

### ISSUE THREAD

**Issue by reitermarkus** [k8s-at-home/charts#1395]
# Details

I cannot run `./hack/gen-helm-docs.sh` anymore, it fails with:

```
Error generating gotemplates for chart /{{chart}}: template: /{{chart}}:120: function "fromYaml" not defined
```

Apparently, this is since it now requires the change in https://github.com/k8s-at-home/helm-docs/commit/6e5b1f9b265d32c9f3179fe1d7df4304a73ec6f4 which is not in upstream `helm-docs`.

**Comment by onedr0p** [comment]
In our docs, we mention to use our fork of helm-docs. Hopefully this will be PR'd upstream one day and merged in :)

https://docs.k8s-at-home.com/our-helm-charts/development/creating-a-new-chart/#dependencies

**Comment by reitermarkus** [comment]
> In our docs, we mention to use our fork of helm-docs. 

Well, I read those docs and installed `helm-docs` from upstream a month or two ago and this was changed 28 days ago, so that explains why I missed it.

> will be PR'd upstream one day

I guess there was an almost an attempt 😄: https://github.com/norwoodj/helm-docs/pull/120

**Comment by bjw-s** [comment]
Yeah, that was a mistake, those were still the WIP changes. Will open up an upstream discussion on how to make the changes 'nice' enough to merge them eventually.

I've actually been working on upgrading our CI yesterday to completely remove that step from the local dev flow. That is almost done and we'll update the docs accordingly. Hopefully that makes life easier for contributors.
