### ISSUE TITLE
[samba] Unmaintained image with security flaws

### ISSUE THREAD

**Issue by runningman84** [k8s-at-home/charts#1401]
# Details

**Helm chart name and version:**
samba

**Container name and tag:**
dperson/samba

The docker image suffers from security issues like https://github.com/dperson/samba/issues/407.

I have't found a better docker image yet, this looks promising but there are k8s issues:
https://github.com/crazy-max/docker-samba

I think a special docker image and a configmap for the smb.conf and secrets for the users might be a better longterm solution.

**Comment by bjw-s** [comment]
I'd be fine with switching it out for a more maintained image. 

Could you be more specific about the k8s issues with the alternative you provided? 
It seems that it can be configured with ENV vars and a yaml file (can be provided by either configMap or Secret). That would make it work pretty well I'd think?

**Comment by runningman84** [comment]
I have seen this issue but I haven't double checked it:
https://github.com/crazy-max/docker-samba/issues/12

**Comment by bjw-s** [comment]
This person has mounted a configMap to the /data folder. But configMaps are _always_ read-only. If the configuration has to be mounted to a path inside /data, ideally a subPath should have been  used.

**Comment by runningman84** [comment]
/data should be emptydir and the configfile a subpath

**Comment by bjw-s** [comment]
Sounds about right 👍🏻
