### ISSUE TITLE
Metrics don't mount /config correctly if subPath: used in main persistence

### ISSUE THREAD

**Issue by szinn** [k8s-at-home/charts#1417]
# Details

**Helm chart name and version:**
This is with Sonarr chart 16.0.0 but it appears to also be with Radarr 16.0.0 and Lidarr 14.0.0 and possibly any other chart that uses the same metrics exporter.

**Container name and tag:**

**What steps did you take and what happened:**

Created a pvc and mounted a subpath of it for the config and enabled metrics. The exporter cannot find /config/config.xml

**Relevant Helm values:**

    persistence:
      config:
        enabled: true
        existingClaim: media-config-lh-pvc
        subPath: sonarr
    prometheus:
      podMonitor:
        enabled: true
        interval: 10m
        scrapeTimeout: 2m
    metrics:
      enabled: true
      prometheusRule:
        enabled: true

**What did you expect to happen:**

Both containers (Sonarr and exporter start correctly)

**Anything else you would like to add:**

In the generated Deployment entity, the Sonarr container has the volumeMounts configured as:
          volumeMounts:
            - name: config
              mountPath: /config
              subPath: sonarr

however in the exporter container, the subPath is missing. I verified that by adding it in, the exporter container starts correctly.

**Additional Information:**

**Comment by onedr0p** [comment]
This was also reported here https://github.com/k8s-at-home/charts/issues/1281

If you can please submit a PR to the radarr, Sonarr and Lidarr charts. That would be very helpful!

**Comment by szinn** [comment]
Figured out how to fork and do a test. PR submitted for Sonarr and working on Lidarr and Radarr as they have the same issue.

**Comment by onedr0p** [comment]
You can do them all in the same PR if that is easier for you

**Comment by onedr0p** [comment]
Nevermind, looks like you opened separate, that's ok.

**Comment by szinn** [comment]
Yes, saw the contributing note that said they should go separately.

A recommendation would be to add a "how to fork and set up an environment".

**Comment by onedr0p** [comment]
Looks like you need to include the changelog annotation in each Chart.yaml

**Comment by onedr0p** [comment]
Sorry I should have been a bit more clear, see here for an example:

https://github.com/k8s-at-home/charts/pull/1418/files#diff-6fc1aec569b0894deffee2c04746239b92f999f2b07d4e9e0beaaaf1bb8d2169R20-R23

These annotations are then displayed on artifacthub.

**Comment by szinn** [comment]
Sorry for the double commit on each - read your comment wrong and initially did it with -kind: changed rather than added.
