### ISSUE TITLE
Vaultwarden Chart not working on microk8s

### ISSUE THREAD

**Issue by falknerdominik** [k8s-at-home/charts#1437]
# Details

Chart: [vaultwarden](https://artifacthub.io/packages/helm/k8s-at-home/vaultwarden), version 4.0.1
Image: vaultwarden/server:1.24.0

Followed the instructions [here](https://artifacthub.io/packages/helm/k8s-at-home/vaultwarden)

Logs of the container

```
/--------------------------------------------------------------------\
|                        Starting Vaultwarden                        |
|                           Version 1.24.0                           |
|--------------------------------------------------------------------|
| This is an *unofficial* Bitwarden implementation, DO NOT use the   |
| official channels to report bugs/features, regardless of client.   |
| Send usage/configuration questions or feature requests to:         |
|   https://vaultwarden.discourse.group/                             |
| Report suspected bugs/issues in the software itself at:            |
|   https://github.com/dani-garcia/vaultwarden/issues/new            |
\--------------------------------------------------------------------/

[INFO] No .env file found.

[2022-02-25 19:14:04.935][vaultwarden][ERROR] Data folder 'config' doesn't exist.
[2022-02-25 19:14:04.936][vaultwarden][ERROR] Create the data folder and try again.
```

**What did you expect to happen:**
Services starts

**Anything else you would like to add:**

**Additional Information:**

**Comment by onedr0p** [comment]
Really hard to help without you posting your helm values and any additional configuration ;)

**Comment by falknerdominik** [comment]
Nothing additional and that was the problem. The chart states later in the documentation that a persistent configuration is needed. When applying that it work out of the box.
Copied directly from the doc:
```
persistence:
  config:
    enabled: true
    type: emptyDir
```

Sorry for not reading more into it (played around it for half an hour before finding it)

**Comment by onedr0p** [comment]
Just know that emptyDir will not persist across restarts of the container, you should use something for persistent storage.
