### ISSUE TITLE
home-assistant - external database support

### ISSUE THREAD

**Issue by voarsh2** [k8s-at-home/charts#1461]
# Details

I have a large Maria Galera cluster running and wanted to install this chart, to save resources I'd like to use my existing DB instances, but this chart only supports provision a standalone instance, I can't use an external one that is already provisioned.

**Helm chart name:** 
home-assistant

**Describe the solution you'd like:**

Add support for specifying remote DB host/ip and to not provision a DB statefulset

**Comment by onedr0p** [comment]
You do not need to enable the db in the helm chart values, there's likely tons of people using this chart with an external db. You only need to configure the app to consume an external db via reading their docs.
