### ISSUE TITLE
[mosquitto] Add per_listener_settings option to configmap for mosquitto.conf

### ISSUE THREAD

**Issue by greg-mcnamara** [k8s-at-home/charts#1516]
# Details

**Helm chart name:**
mosquitto

**Describe the solution you'd like:**
Mosquitto now includes an option to define security settings per listener. While the chart allows additional config files to be added, and therefore additional listeners can be defined, the "per_listener_settings" option must be configured before any of the applicable settings are defined for any listener, so it must be included in the default configmap generated by the chart. If per_listener_settings is added to an additional config file, an error occurs and mosquitto does not start up. I suggest that the chart should include a per_listener_settings (true/false) top-level option to add the setting to the first line of the default mosquitto configuration.

**Anything else you would like to add:**

**Additional Information:**

**Comment by bjw-s** [comment]
I've created a PR that should implement this feature.
