### ISSUE TITLE
accessMode is required for PVC

### ISSUE THREAD

**Issue by JuezFenix** [k8s-at-home/charts#1518]
# Details

**Helm chart name and version:**

Radarr v16.1.0 (and others)

**What steps did you take and what happened:**

When set persistence true in many charts we get this error.  Error: INSTALLATION FAILED: execution error at (radarr/templates/common.yaml:50:3): accessMode is required for PVC radarr-media

**Relevant Helm values:**

persistence:
  config:
    enabled: true

  media:
    enabled: true
    mountPath: /media

**What did you expect to happen:**

Create deploy with persistence.

**Comment by onedr0p** [comment]
It seems like you are not providing enough information to the persistent block.

Please check out our docs

https://docs.k8s-at-home.com/our-helm-charts/common-library-storage/

**Comment by JuezFenix** [comment]
I see, but when i try to install i get:

`Error: INSTALLATION FAILED: library charts are not installable`

I'm ussing Lens.

**Comment by onedr0p** [comment]
Sounds like a Lens problem then.

**Comment by JuezFenix** [comment]
I have tried using helm on console, same result.

`helm install common k8s-at-home/common -n mediaserver
Error: INSTALLATION FAILED: library charts are not installable
`

**Comment by onedr0p** [comment]
Why are you trying to install the library chart?

https://docs.k8s-at-home.com/our-helm-charts/common-library/

> The Common library chart is not meant to be installed directly, application charts use the Common library as a dependency.

Please read thru the docs.

**Comment by bjw-s** [comment]
As stated by @onedr0p, the library chart is not meant to be installed directly. The installation instructions for all charts are included in their respective README.md files. For Radarr this would be https://github.com/k8s-at-home/charts/tree/master/charts/stable/radarr#tldr.
