### ISSUE TITLE
pod-gateway wrong default for vpn sidecar ?

### ISSUE THREAD

**Issue by lucacalcaterra** [k8s-at-home/charts#1525]
Default values for openvpn sidecar  are setted with openvpn port 443 and protocol UDP, seems not correct for me (usually 1194 UDP and 443 TCP)
Changing network policy (in my case to honorate 1194 UDP) openvpn works .

Can you confirm me ?

Thanks

**Comment by angelnu** [comment]
Thanks for reporting @lucacalcaterra - it is indeed an inconsistent default so I did a PR to change it.
