### ISSUE TITLE
[games-on-whales] error: could not open displa

### ISSUE THREAD

**Issue by qiaouchicago** [k8s-at-home/charts#1549]
### Helm chart name

games-on-whales

### Helm chart version

1.7.0

### Container name

xorg

### Container tag

1.0.0

### Description

kubectl logs games-on-whales-78874f7c64-jcglq xorg           
Allow /dev/uinput r/w to the group
Adding user 'root' to groups: kvm,root
Starting Xorg (:99)

X.Org X Server 1.20.11
X Protocol Version 11, Revision 0
Build Operating System: linux Ubuntu
Current Operating System: Linux o790m 5.13.0-39-generic #44~20.04.1-Ubuntu SMP Thu Mar 24 16:43:35 UTC 2022 x86_64
Kernel command line: BOOT_IMAGE=/boot/vmlinuz-5.13.0-39-generic root=UUID=ae38c794-c9d3-4585-ae59-59908545c16c ro quiet splash vt.handoff=7
Build Date: 06 July 2021  10:17:51AM
xorg-server 2:1.20.11-1ubuntu1.1 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.40.0
	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
	(++) from command line, (!!) notice, (II) informational,
	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.99.log", Time: Tue May  3 00:05:07 2022
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
vesa: Ignoring device with a bound kernel driver
(EE) 
Fatal server error:
(EE) AddScreen/ScreenInit failed for driver 0
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
	 at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/var/log/Xorg.99.log" for additional information.
error: could not open display
(EE) 
(EE) Server terminated with error (1). Closing log file.

### Expected result

xorg should be running healthy

### Helm values to reproduce

```YAML
Used default values
```

**Comment by onedr0p** [comment]
The configuration for this app is pretty intense, I would take a look at @angelnu helm values for ideas

https://github.com/angelnu/k8s-gitops/blob/main/apps/default/gow/release.yaml
