### ISSUE TITLE
[vikunja] document postgresql values

### ISSUE THREAD

**Issue by Patricol** [k8s-at-home/charts#1571]
### Helm chart name

vikunja

### Describe the solution you'd like

Mention postgresql.enabled in values file, readme, etc.

### Additional Information

Spent quite a while trying to figure out why chart was bugging out; trying to create multiple services with the same name. Searching in values, templates, and library-chart values didn't help. Needed to notice postgresql was added as a dependency in Chart.yaml

**Comment by bjw-s** [comment]
We've (very) recently come to the decision that we will be deprecating the use of the database dependency charts and rather let the chart user decide how they wish to deploy their database (with a lifecycle separate from the main application chart).

**Comment by bjw-s** [comment]
See https://github.com/k8s-at-home/charts/issues/1572 for more background on the decision.

**Comment by xeruf** [comment]
Something is weird there though - for me it creates a postgresql pod even though I did not enable it, but it also does not configure vikunja to use it, so the pod is running without purpose...

**Comment by xeruf** [comment]
yes, this is very confusing. The default configuration will use a transient SQLite database, which is a very bad idea...
