### ISSUE TITLE
[CI] Upgrade CI to use newer K3S kid cluster version

### ISSUE THREAD

**Issue by samip5** [k8s-at-home/charts#1599]
### Helm chart name

N/A / CI

### Describe the solution you'd like

I would like the CI to be upgraded to 1.22 k3s cluster that it uses.

**Comment by bjw-s** [comment]
We would all like that. But since our charts currently target older versions we are not (yet) able to do so.

But as usual, PR's (instead of oneliner issues) are welcomed!
