### ISSUE TITLE
Arm support via linuxserver/plex

### ISSUE THREAD

**Issue by benmichael** [k8s-at-home/charts#16]
As this project largely serves home projects, a fair number of the audience may be using arm based SBC clusters (especially with there now being an 8GB Raspberry Pi).

I am aware that the Plex maintained docker images only cater to x86, however the linuxserver.io images include arm images. 

While it may require significant effort to cleanly migrate, my proposal would be to do so, so as to cater to a wider audience. 

While it would mean moving away from the official images, linuxserver.io has a good reputation for maintaining high quality images. 

https://hub.docker.com/r/linuxserver/plex/

**Comment by carpenike** [comment]
@benmichael — FYSA, note the new chart repo location for your PR.

**Comment by radum** [comment]
@benmichael I have been using the linuxserver images with this charts for quite a while now and all works great.

And I have a 8GB Pi running on Ubuntu x64 for Pi.

**Comment by carpenike** [comment]
Cool, will go ahead and close this issue then.

Cheers!
