### ISSUE TITLE
[pod-gateway] Cannot install the chart

### ISSUE THREAD

**Issue by ameyp** [k8s-at-home/charts#1698]
### Helm chart name

pod-gateway

### Helm chart version

latest

### Container name

gateway-admision-controller

### Container tag

v3.5.0

### Description

When I run 

```
helm upgrade --install pod-gateway k8s-at-home/pod-gateway
```

I get the following error:

```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(Deployment.spec.template.spec.containers[0].args[10]): invalid type for io.k8s.api.core.v1.Container.args: got "map", expected "string", ValidationError(Deployment.spec.template.spec.containers[0].args[14]): invalid type for io.k8s.api.core.v1.Container.args: got "map", expected "string"]
```

### Expected result

I expect the installation to succeed

### Helm values to reproduce

```YAML
None
```

### Additional Information

I generated the template and took a look, the two problematic args are:

args[10]
```
- --initImage=ghcr.io/k8s-at-home/pod-gateway:
```

args[14]
```
- --sidecarImage=ghcr.io/k8s-at-home/pod-gateway:
```

**Comment by bjw-s** [comment]
Thanks for creating this bug report! I had a look and there were some defaults missing. I've added these in version 5.5.1 of the chart which should be publishing soon.

Should this not fix the issue please feel free to reopen the bug report.
