### ISSUE TITLE
[esphome] Invalid default image tag in chart

### ISSUE THREAD

**Issue by carpenike** [k8s-at-home/charts#17]
Default tag (https://github.com/billimek/billimek-charts/blob/master/charts/esphome/values.yaml#L7) is invalid.

Not a huge fan of the esphome [tags](https://hub.docker.com/r/esphome/esphome/tags), looks like they're commit IDs which will make automated updates a nightmare.

**Comment by nolte** [comment]
#70 will be update the default tag and the appVersion to [1.15.2](https://hub.docker.com/layers/esphome/esphome/1.15.2/images/sha256-2fb5cbff856fc7fb408d772ebaee9311c613b8552decb9d1bc6e1a73ef6f6e3e?context=explore)

**Comment by carpenike** [comment]
Resolved by #70
