### ISSUE TITLE
[common] Enhancements / bug fixes to common library chart

### ISSUE THREAD

**Issue by bjw-s** [k8s-at-home/charts#173]
Created this issue as a container issue, to more easily keep track of the things we need/want to fix on the common library chart, but that are not strictly neccessary right away and/or don't really warrant an issue of their own.

- [x] `{{ template common.whatever . }}` pattern is best replaced by `{{ include common.whatever . }}`, according to official [Helm docs](https://helm.sh/docs/chart_template_guide/named_templates/#the-include-function)
- [ ] Helm named templates should all have a docstring (for lack of a better word) that describes what it does and what the expected input is (if applicable)
- [x] `service.port.targetPort` is a string in the provided `values.yaml` file. Merging in user overrides *could* cause an error when an integer is given due to conflicting data types.
- [x] `README.md` improvements are required
- [x] Add support for `hostNetwork`
- [x] Add support for `hostAliases`
- [x] Add support for daemonset controller (https://github.com/k8s-at-home/charts/pull/178/commits/34df5b8fb599cac7c705efe91e3262f5a035e289)
- [x] Add support for specifying and creating chart-specific serviceAccount (https://github.com/k8s-at-home/charts/pull/178/commits/836b5de03ddb5eb300faf460aeb4dc5ce3174bff)

**Comment by onedr0p** [comment]
We should target the above for a `1.6.0` release

**Comment by onedr0p** [comment]
`service.port.targetPort` could be a string or a number I wonder how we can make it generic.

**Comment by bjw-s** [comment]
> `service.port.targetPort` could be a string or a number I wonder how we can make it generic.
One solution could be to leave it empty in `values.yaml`, and put in a default value (`http`?) in the service class `.tpl` file

**Comment by onedr0p** [comment]
> One solution could be to leave it empty in values.yaml, and put in a default value (http?) in the service class .tpl file

Done in https://github.com/k8s-at-home/charts/commit/bb98d0cda5b97effa47a0d696832398339e1a40d
