### ISSUE TITLE
[unifi] Enable external deployment of mangoDB

### ISSUE THREAD

**Issue by tingvarsson** [k8s-at-home/charts#177]
As the title says, feature request to enable the possibility to deploy an external db. Either as separate pod (e.g. helm chart dependency) or completely external by e.g. host/user/pass configuration.

**Comment by onedr0p** [comment]
@tingvarsson there any documention you can link to in the README on how to set this up? You could add mongo as a dependency in the Chart.yaml

**Comment by tingvarsson** [comment]
Ok, so I looked some more at it this morning and it seems quite simple to actualize. We already expose the DB configuration parameters in the chart, and we can disable the internal DB. So what would be nice as an alternative to run it completely seperate is to be able to spin it up as a pod within this chart. Similar to how [nextcloud](https://github.com/nextcloud/helm/tree/master/charts/nextcloud) does it with their DB. I.e. It can be setup as internal, external but as a chart dependency, or completely external/deployed seperately.

Here's the small note in upstream [README](https://github.com/jacobalberty/unifi-docker/tree/stable-5#running-with-separate-mongo-container)
And here's a [docker-compose](https://github.com/jacobalberty/unifi-docker/blob/stable-5/docker-compose.yml) example running with a separate mongo DB.

**Comment by Ornias1993** [comment]
@tingvarsson might I suggest the worse docker container available, might not be the best example to give?
When it comes to updating and data storage it totaly fucks up ALL docker best-practices.
I think those people are not the example you want to give :')

That being said, seperating MongoDB for Unifi does make it more docker-friendly to keep track of the versioning between unificontroller and MongoDB for "normal" docker/k8s devops.

**Comment by Ornias1993** [comment]
Definately still a relevant and not stale.

**Comment by onedr0p** [comment]
@Ornias1993 I've heard doing this outside kubernetes is a pain in the ass, and very fragile. I can't see deploying it in kubernetes will make it any easier / stable. Not sure we want to keep this issue open if OP or no-one chooses to work on it.

**Comment by ishioni** [comment]
I've had the capability in my own chart for this. However, I'd discourage it for two reasons
#1 The bitnami chart is not that great to work with, it leaks memory all the time, and no, setting wiredtigercachesizegb doesn't seem to help
#2 The official mongo image doesn't work on armv7, while unifi does. This creates a problem where people on older SBCs (Pi3B) might not be able to use the chart. I understand that might not be a big userbase, but i'd still be wary

However, if there is a technical need for this, I'm willing to port my work

**Comment by Ornias1993** [comment]
@ishioni I think thats a pretty solid foundation why it shouldn't be done. Thank!
Doing things just "because we can", only leads to future issues along the road and I don't see many people interested in this feature stepping up to fix them (as they also didn't send in a PR)

**Comment by bjw-s** [comment]
Looks like the consensus is that this is not something we should pursue any further right now.
If a need for this does rise in the future, feel free to leave a comment or open a new issue 👍
