### ISSUE TITLE
[node-red] regression of 'hostAliases' value

### ISSUE THREAD

**Issue by coldfire84** [k8s-at-home/charts#183]
With release of Node-RED template 4.0.0/ "common library" the recent [PR for hostAliases](https://github.com/k8s-at-home/charts/pull/150)  support looks to have been lost.

**Comment by bjw-s** [comment]
This is correct. Re-implementation is scheduled to be included with common library version 1.6.0.

**Comment by onedr0p** [comment]
as @bjw-s mentioned, we will hopefully have this back in the chart soon with the common library update. 
Until then please stay with your current version :)

**Comment by bjw-s** [comment]
This one should be fixed now. Please let us know if it's not :-)
