### ISSUE TITLE
Possibility of adding https://github.com/guillaumedsde/alpine-qbittorrent-openvpn

### ISSUE THREAD

**Issue by blmhemu** [k8s-at-home/charts#20]
Hey ! I was trying to add a chart with [this](https://github.com/guillaumedsde/alpine-qbittorrent-openvpn) image.
I was able to modified your qbittorrent chart with some success. The issue being, I was able to curl from one of the nodes but not another (I have a 2 node setup using k3s. Curl in master node was giving operation timeout where as a curl in worker node was working just fine for the same clusterIP.). As a result, nginx ingress was giving timeout.
Other charts seems to be working fine under the same conditions. 

Hope you can help me. Thank you.

**Comment by onedr0p** [comment]
@blmhemu ... @bjw-s has upgraded the chart for qbittorrent to include a openvpn / wireguard container.

I have also created a [container images](https://github.com/k8s-at-home/container-images) in our org here that include a startup script for checking if the vpn is active.


For example, seeing these 2 things work together checkout @bjw-s deployment [here](https://github.com/bjw-s/k8s-gitops/tree/master/deployments/downloads/qbittorrent)
