### ISSUE TITLE
[home-assistant] RFC: Enable External Management of secrets.yml

### ISSUE THREAD

**Issue by carpenike** [k8s-at-home/charts#23]
Was IM'ing with @onedr0p on Discord and chatting on how we could somehow lock down the secrets.yml file so that everything can be stored in public git.

Considering the use of an initContainer that pulls down an entire hass config from a public git repo. The secrets.yml file would be encrypted with either git-crypt (https://github.com/AGWA/git-crypt) or SOPS (https://github.com/mozilla/sops) and would be unlocked as part of the init process.

Would require us to maintain an initContainer that could perform most of this heavy lifting, although I anticipate that will be small.

Thoughts?

**Comment by lexfrei** [comment]
My PR #305 implements this for appdaemon. 
I'm already using this syntax for Traefik and it looks fine for me
https://github.com/lexfrei/k8s/blob/a5beec1a2ddd60202f91aac2beeadeb9caa7ba5e/helmfile.d/traefik.yaml#L47-L52

Isn't it enough?

**Comment by onedr0p** [comment]
Closing this issue, we have improved git-crypt support since then.

@carpenike feel free to re-open if you think something else needs to be added.
