### ISSUE TITLE
Add Intel GPU Device plugin chart

### ISSUE THREAD

**Issue by WojoInc** [k8s-at-home/charts#29]
I plan on working on munnerz/kube-plex#12. I figured if the issue of getting worker pods to consume GPU resources works, a chart to make deployment of the [Intel GPU plugin](https://github.com/intel/intel-device-plugins-for-kubernetes/blob/master/cmd/gpu_plugin/README.md#installation) easier could be helpful.
This would also work with k8s-at-home/charts/plex, even for those not using worker pods, by adding:
```yaml
resources:
  requests:
    gpu.intel.com/i915: 1
```
Any thoughts @billimek and @onedr0p ?

**Comment by onedr0p** [comment]
Go for it!

**Comment by bjw-s** [comment]
@WojoInc I see that you self-assigned this issue some time ago. Did you happen to make any progress? Or would you be OK if I picked it up?

**Comment by WojoInc** [comment]
Hi there! Been getting swamped with work lately unfortunately...
Go for it! I'm happy to help test anything if needed. 🙂

**Comment by bjw-s** [comment]
Should be implemented by #76. If there's something missing, let me know :)
