### ISSUE TITLE
[photoprism] add postgresql and mariadb as a dep

### ISSUE THREAD

**Issue by carpenike** [k8s-at-home/charts#291]
Running list of features for PhotoPrism.

Initial PR #290 is intended to provide base functionality. 

Add the following

- [x] Allow for the use of an existingSecret for envVars.
- [ ] Add a dependent chart for Mariadb
- [ ] Add a dependent chart for Postgres

**Comment by onedr0p** [comment]
Postgres supported? I see you have mariadb already.

The 1.8.0 common lib will add `envFrom` will that solve the first issue?

**Comment by ryholt** [comment]
I believe it is in the dev branch: https://github.com/photoprism/photoprism/commit/6577d99363cd9d9013444b1fbd95efe488634901

Yeah the `envFrom` should solve it.

**Comment by carpenike** [comment]
Postgres is coming-ish. They're tracking it: https://github.com/photoprism/photoprism/commit/6577d99363cd9d9013444b1fbd95efe488634901

Looks like it requires an update to GoRM

1.8.0 for common will solve top item.
