### ISSUE TITLE
[sabnzb] Issue when using ingress during initial setup

### ISSUE THREAD

**Issue by EugenMayer** [k8s-at-home/charts#306]
Latest sabnzb chart - it is a well know issue we might want to put here into the readme. Without re-describing it in other words, this one nails it down: https://github.com/linuxserver/docker-sabnzbd/issues/73#issuecomment-653840511

The current chart here does cause the same issue when using an ingress from the start.

I'am not sure we can do anything about that beside setting the hostname whatever the ingress host is, but this might get complicated. At least we should make the users aware about what will happen and how to fix this ( using port-forward on 8080, setup whitelist ... back to ingress ). 

Thanks!

**Comment by onedr0p** [comment]
You are right. This is more of an upstream issue with the app.

We could however do something like we do for the qbittorrent chart which modifies the config file and updates the bittorrent port. We could do something like that with the whitelist domain for sabnzbd possibly.

**Comment by EugenMayer** [comment]
@onedr0p maybe do it in to steps, ,the short term is adding a README statement about what will happen with the error message, and how to deal with it.

In the second step maybe find out how to manipulate the configuration and sync it with the ingress setting. I think this will take long or long, thus the README statement first (which we can remove afterwards easily).

**Comment by onedr0p** [comment]
@EugenMayer I added documentation to the readme but I am still unsure about adding a initContainer to solve this problem. If anyone has interests in doing so PRs are welcome.
