### ISSUE TITLE
[common] Add support for other probe types

### ISSUE THREAD

**Issue by bjw-s** [k8s-at-home/charts#312]
# Details

**Helm chart name:** `common`

**Describe the solution you'd like:**

Currently only `tcpSocket` type is supported as liveness/readiness/startup probe. We should add support for the `httpGet` and `exec` types.

**Anything else you would like to add:**

N/A

**Additional Information:**

N/A

**Comment by onedr0p** [comment]
Done in https://github.com/k8s-at-home/charts/pull/316
