### ISSUE TITLE
[common] Missing fullnameOverride in values

### ISSUE THREAD

**Issue by bjw-s** [k8s-at-home/charts#314]
# Details

**Helm chart name and version:** common 1.7.0

**Container name and tag:** N/A

**What did you expect to happen:**

`values.yaml` should have an entry for `fullnameOverride` to indicate availability of the option

**Anything else you would like to add:**

N/A

**Additional Information:**

N/A

**Comment by onedr0p** [comment]
Done in https://github.com/k8s-at-home/charts/pull/316

Also added `nameOverride` to `values.yaml`
