### ISSUE TITLE
Chart migration to use media-common

### ISSUE THREAD

**Issue by DirtyCajunRice** [k8s-at-home/charts#37]
Candidate charts that would work as an umbrella templated media-common chart
- [ ] bazarr
- [ ] nzbget
- [ ] sabnzbd
- [ ] dashmachine

(are there more? will add to the list as needed)

**Comment by carpenike** [comment]
Could add dashmachine if organizrr is apart of it.

**Comment by bjw-s** [comment]
I'll take a crack at migrating nzbget

**Comment by bjw-s** [comment]
It doesn't like we'll be able to do a 1:1 migration of nzbget because of the integrated OpenVPN container :( That may be be resolved by some sort of `additionalContainers` directive in media-common, but is that a direction we're willing to go? It will make media-common a super flexible chart template, but maybe that defeats its' purpose.

**Comment by DirtyCajunRice** [comment]
@bjw-s  so check this out. The point was to be able to swiss-army-knife other stuff into it. My proposal:
Make a openvpn library chart that is added as a dependency when requested and we can add an `additionalContainers` section like you said where this will utilize that and inject it in.

**Comment by bjw-s** [comment]
Now that #45 is in, the only thing I'm still wondering about is the `downloads` volume that is currently in place for nzbget (and probably the other downloader-type charts). Directions we could take this:

- direct users to use the `media` volume from _media-common_ for their downloads location
- direct users to provide their own PVC and use the additionalVolumes and additionalVolumeMounts option
- add a `downloads` volume to _media-common_ similar to `media`

I have a slight preference for option 3 in this case, but I'm curious about your take

**Comment by CuBiC3D** [comment]
nzbhydra2 also fits the pattern
