### ISSUE TITLE
Where is the code of cloudflare dyndns?

### ISSUE THREAD

**Issue by danielo515** [k8s-at-home/charts#39]
Hello,
I am missing some config options for the cloudflare dyndns chart, specifically CF_APITOKEN. This is used to provide a more restricted token so the app has much more limited access.
Because it is not documented, I decided to take a look at the chart code, but I was not able to find it.
Where is it? And, will you consider adding this configuration options?
Thanks and regards

**Comment by onedr0p** [comment]
Hi @danielo515 IIRC I had it removed because I couldn't get it working. We're open to bring the chart back if you wanted to open a PR.

**Comment by danielo515** [comment]
Hello @onedr0p ,what do you mean by not working? Not working at all or behaving incorrectly? Or do you refer to the tokens that I specifically mentioned? I have it mine running and the logs shows a normal operation, so unless it is not working but showing promising logs It is working for me

**Comment by onedr0p** [comment]
I found the PR in which I removed it.

https://github.com/billimek/billimek-charts/pull/148

Feel free to open a PR to add it back.
