### ISSUE TITLE
[node-feature-discovery] Deprecate chart after PR is merged upstream

### ISSUE THREAD

**Issue by onedr0p** [k8s-at-home/charts#424]
# Details

**Helm chart name:**

node-feature-discovery

**Describe the solution you'd like:**

Deprecate node-feature-discovery chart after the following is merged

https://github.com/kubernetes-sigs/node-feature-discovery/pull/423

**Comment by onedr0p** [comment]
Upstream chart still not released

**Comment by nikdoof** [comment]
Upstream has been merged but not released yet. Release v0.8.0 tracking is in kubernetes-sigs/node-feature-discovery#437

**Comment by bjw-s** [comment]
Two more PR's to go according to https://github.com/kubernetes-sigs/node-feature-discovery/issues/437#issuecomment-799525058 🙂

**Comment by CuBiC3D** [comment]
It's released now
