### ISSUE TITLE
(feat): smb chart

### ISSUE THREAD

**Issue by lukasmrtvy** [k8s-at-home/charts#437]
# Details

**Helm chart name:**

samba

**Describe the solution you'd like:**

would be nice to have also samba chart, this will replace need of freenas, omv or samba standalone package ( multitenancy and ha will not work tho, but its ok for home usage ) .. 

related:
- https://github.com/kubernetes-csi/csi-driver-smb/tree/master/deploy/example/smb-provisioner
- https://gandazgul.github.io/k8s-infrastructure/charts/samba/

**Anything else you would like to add:**

no

**Additional Information:**

no

**Comment by bjw-s** [comment]
I'll see if I can whip something up in the coming days. Currently already running it as a deployment/service, so should be able to get it working 😄

**Comment by bjw-s** [comment]
Closing this issue. An initial version has been released via #477 . 
We can iterate on that if required. If so, we should maybe collect some ideas first through the [Github Discussions](https://github.com/k8s-at-home/charts/discussions) pages.
