### ISSUE TITLE
(question): official slack channel

### ISSUE THREAD

**Issue by lukasmrtvy** [k8s-at-home/charts#439]
Would be nice to have official Slack(?) channel, instead of spaming github repository.

https://kubernetes.slack.com/ will be probably good enough for a start
( https://github.com/kubernetes/community/blob/master/communication/slack-guidelines.md#requesting-a-channel )

Thanks

**Comment by onedr0p** [comment]
@lukasmrtvy we have our own Discord server. I'm not sure how much benefit there is splitting up the discussions into two different platforms. 

This is something that should be discussed here anyways

https://github.com/k8s-at-home/charts/discussions
