### ISSUE TITLE
[oauth2-proxy] Support ingressClassName field

### ISSUE THREAD

**Issue by agileman-droid** [k8s-at-home/charts#449]
# Support ingressClassName in the oauth2-proxy Ingress

**Helm chart name:** oauth2-proxy

**Describe the solution you'd like:** 

Since Kubernetes 1.18, the `kubernetes.io/ingress.class` Ingress annotation is deprecated. We normally used this annotation to assign specific Ingresses to specific ingress controllers. Now, the `ingressClassName` should be used instead for that purpose.

It would be nice if the **oauth2-proxy** Helm chart added an option to customize the `spec.ingressClassName` field on the Ingress.

**Anything else you would like to add:**

- [Kubernetes blog -- Improvements to the Ingress API in Kubernetes 1.18](https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#extended-configuration-with-ingress-classes)
- [IngressSpec v1beta1 API reference](https://v1-18.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#ingressspec-v1beta1-networking-k8s-io)

**Additional Information:**

**Comment by Diaoul** [comment]
Just found out this chart in particular doesn't support `ingressClassName`
