### ISSUE TITLE
[home-assistant] chart can't be downloaded

### ISSUE THREAD

**Issue by Vaproc** [k8s-at-home/charts#452]
# Details

**Helm chart name and version:**
home-assistant 5.2.2

**Container name and tag:**
Defined _homeassistant/home-assistant:2020.12.1_ in chart, but not deployed

**What steps did you take and what happened:**
```
$ helm repo add k8s-at-home https://k8s-at-home.com/charts/
$ helm repo update
$ helm install k8s-at-home/home-assistant
Error: failed to download "home-assistant" (hint: running `helm repo update` may help)
```

**What did you expect to happen:**
Helm chart _Home Assistant_ gets deployed successfully

**Anything else you would like to add:**
It looks to me that some YAMLs in templates/ are missing

**Additional Information:**
none

**Comment by onedr0p** [comment]
I think something is borked on your end:

```
$ helm repo add k8s-at-home https://k8s-at-home.com/charts/
$ helm repo update
$ helm search repo k8s-at-home | grep home-assistant
k8s-at-home/home-assistant              5.2.2           2020.12.1               Home Assistant
```

**Comment by onedr0p** [comment]
Additionally

```
$ helm pull k8s-at-home/home-assistant
$ ls -la home*
-rwxrwxrwx 1 devin devin 143558 Dec 31 08:40 home-assistant-5.2.2.tgz*
```
