### ISSUE TITLE
A way to specify different container port and service port?

### ISSUE THREAD

**Issue by FlipEnergy** [k8s-at-home/charts#465]
# Details

**Ask your question:**

So I tried spinning up the Navidrome chart and noticed that `service.port.port` must be specified to the port the app container is listening on. However, this is also the same port that will be bound to the service for listening.

I'd really like a way for these to be different, for example Navidrome listens on 4533, so I must specify `service.port.port` to be 4533 but I'd like my service to listen on port 80 because I use type LoadBalancer and would like to map to port 80 for each service IP. Is there a way to do this currently?

**Comment by bjw-s** [comment]
Currently that is not supported in our charts. If I understand correctly, you want to expose port 80 and map it to port 4533 in the main container?

**Comment by FlipEnergy** [comment]
That's right. I can make a feature request issue if you think it's worth it. I'd like to be able to expose one port on the service, and forward that, or map it as you said, to a different port in the main container.

**Comment by FlipEnergy** [comment]
Wow Thanks! I may throw in a quick pr to update Navidrome to common 2.2.0.

**Comment by onedr0p** [comment]
> Wow Thanks! I may throw in a quick pr to update Navidrome to common 2.2.0. 

Renovatebot should handle this for us, it will take sometime to run thru all the charts though

**Comment by onedr0p** [comment]
We should be all set here with common 2.2.0, closing.
