### ISSUE TITLE
[plex] How can I tweak the values for direct NFS mount not pv on NFS

### ISSUE THREAD

**Issue by goku-son** [k8s-at-home/charts#478]
I am a complete noob as far a Kubernetes and Helm. I would like to use my existing data folder with all my media for movies and tvseries with the deployment. These live on an existing NFS server. 

I made the following changes to the data volume in the values.yaml:

> data:
    # We want to enable a data pvc
    enabled: true
    # Optionally specify claimName to manually override the PVC to be used for
    # the data directory. If claimName is specified, storageClass and size are
    # ignored.
    ## claimName: "plex-data-pvc"
    # Optionally specify a storage class to be used for the data directory.
    # If not specified and claimName is not specified, the default storage
    # class will be used.
storageClass: "nfs-client"
# subPath: some-subpath
# The requested size of the volume to be used when creating a
# PersistentVolumeClaim.
    #size: 40Gi
# Access mode for this volume
    accessMode: ReadWriteMany
nfs:
server: 10.0.100.90
path: Multimedia/Flixs

 It creates a folder on the NFS share with a pv within it. I would like it to instead just see the existing files and folders within the share instead of creating its own volume within the share. I know that it is total user error on my part so just hoping I could get some guidance on tweaking the syntax to meet my requirements. 
 
Any insights or suggestions would be greatly appreciated.

**Comment by bjw-s** [comment]
With your current settings you are instructing the chart to create a new PVC that contains your data. This chart is not designed to reference NFS volumes directly, but rather references PVC's. 

You can create a PV/PVC that is a reference to your existing NFS share. You can then reference that PVC under `claimName` for the mount that you are trying to create.

This is how mine is set up:
- Chart values: https://github.com/bjw-s/k8s-gitops/blob/main/cluster/media/plex/values.yaml.tmpl
- PV/PVC setup: https://github.com/bjw-s/k8s-gitops/blob/main/cluster/media/_pvc/nas-media.yaml

**Comment by goku-son** [comment]
@bjw-s my apologies for using the wrong template. Your feedback and files you shared helped me correctly configure my set up. 

I am not sure if this is the correct place to ask as my original question was answered. I wanted to use the load balancer configuration you have in your values.yaml file but when I try to do so, it creates two udp services and two tcp services. The udp pods start and the tcp pods stay pending and it’s because of this error:

 Warning  FailedScheduling  26h   default-scheduler  0/3 nodes are available: 3 node(s) didn't have free ports for the requested pod ports.

I think it’s because they are being used by the two udp services but I am not sure why it’s creating 4 (2 tcp 2 udp) instead of two (1 tcp 1 udp):
NAME                                          READY   STATUS    RESTARTS   AGE
sonarr-7d679d8667-92sx8                       1/1     Running   0          10d
radarr-5895898477-mmfcl                       1/1     Running   0          5d3h
ombi-64fb5689bb-25wkv                         1/1     Running   0          5d3h
nfs-nfs-client-provisioner-77b7477884-kzqfm   1/1     Running   0          2d2h
svclb-plex-tcp-7ds5l                          0/4     Pending   0          26h
svclb-plex-tcp-42h26                          0/4     Pending   0          26h
svclb-plex-udp-8h7tr                          5/5     Running   0          26h
svclb-plex-udp-nzz7k                          5/5     Running   0          26h
plex-84bd44d477-nchcq                         1/1     Running   0          26

Here is my values file where I specify the loadblancer configuration:

 Default values
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# The Image to use for PLEX

image:
  repository: plexinc/pms-docker
  tag: 1.20.2.3402-0fec14d92
  pullPolicy: IfNotPresent

#####   START  --> Official PLEX container environment variables
# Override this with the plex claim token from plex.tv/claim
claimToken: ""

# Set the timezone of the plex server
timezone: "America/Chicago"

#####   END  --> Official PLEX container environment variables

# upgrade strategy type (e.g. Recreate or RollingUpdate)
strategyType: Recreate

allowedNetworks:
advertiseIp: "http://10.0.100.9:32400"

serviceTCP:
#  type: ClusterIP
#  port: 32400
   type: LoadBalancer
   externalIPs:
     - 10.0.100.9
   externalTrafficPolicy: Local

serviceUDP:
#  type: ClusterIP
   type: LoadBalancer
   externalIPs:
     - 10.0.100.9
   externalTrafficPolicy: Local

ingress:
  enabled: false

#hostNetwork: false

persistence:
  transcode:
    enabled: false

  data:
    enabled: false

  config:
    claimName: plexconfig-nas
    storageClass: media-nas-media

  extraMounts: 
    - name: nfs-nas-media
      claimName: nfs-nas-media
      mountPath: /storage/media

Any help would be appreciated. If I need to pose this question somewhere else I can do that too. Thanks in advance.

**Comment by bjw-s** [comment]
It's kind of hard to see what is causing it based on this information. It could be that there are some leftovers from another Helm Release still floating around.

If you are on Discord, maybe you can hop on our server? Many people there are running all sorts of setups, so I'm sure one of us could help you get it working there. You can find the server here: https://discord.gg/stmx7vh
Otherwise maybe create a new topic in [our Github discussions page](https://github.com/k8s-at-home/charts/discussions).

I will close this issue for now, since the original question was answered.

**Comment by goku-son** [comment]
@bjw-s thanks for the info much appreciated. I am on discord. If not touch much trouble can you resend me an invite to the discord server? When I click on it it states that the invite is invalid or expired. Thanks in advance.

**Comment by bjw-s** [comment]
Whoops... that link turned out to be bad, sorry about that. This is the correct one :) https://discord.com/invite/7PbmHRK
