### ISSUE TITLE
Cloudflare-ddns still shows on the chart index although it's removed 

### ISSUE THREAD

**Issue by omercnet** [k8s-at-home/charts#486]
# Details
Cloudflare-ddns still shows on the chart index although it's removed 
67167f787c7fbbeefeb16729f2595ee1be98340f

**Container name and tag:**

**What steps did you take and what happened:**

**What did you expect to happen:**

**Anything else you would like to add:**

**Additional Information:**

**Comment by onedr0p** [comment]
I think this is by design with helm charts but we should have used `deprecated: true` in the `Chart.yaml` before deleting it.

**Comment by bjw-s** [comment]
I wonder if this is something we can manually edit in the `index.yaml` or if Chart Releaser action will bork because of the manual intervention 🤔

**Comment by billimek** [comment]
We probably need to manually edit index.yaml in the `gh-pages` branch to remove references to the deleted chart(s).

**Comment by bjw-s** [comment]
Updated the index to remove the deleted package.
