### ISSUE TITLE
Consider a chart for smarter-device-manager

### ISSUE THREAD

**Issue by lazyoldbear** [k8s-at-home/charts#490]
I have recently discovered a wonderful thing made by Alexandre Ferreira from ARM, called Smarter Device Manager. 
It allows to manage host hardware in a normal way, so that:
- there is no more need to have containers privileged
- there is no way to attempt attaching a USB device to different pods

Information:
- https://gitlab.com/arm-research/smarter/smarter-device-manager/-/tree/master
- https://community.arm.com/developer/research/b/articles/posts/a-smarter-device-manager-for-kubernetes-on-the-edge

I have successfuly utilised it on my Intel NUC in microk8s, works with Home Assistant and zwavejs2mqtt, zigbee2mqtt to set up. 

I suggest to consider creating a chart here. And happy to share my humble manifest yamls if relevant.

**Comment by bjw-s** [comment]
Funny you brought this up, I found this one yesterday myself and had a small play around with it. Unfortunately I couldn't get it to work with subpaths (like `/dev/serial/by-id/some-device`) only `/dev/ttyUSB*`, which would be annoying if that means I have to create udev rules to get legible aliases for the devices. How did you tackle that? Maybe you could somehow share your manifests?

**Comment by billimek** [comment]
Also consider taking a look at node-feature-discovery for an alternate approach to solving this problem: https://github.com/kubernetes-sigs/node-feature-discovery

**Comment by lazyoldbear** [comment]
@bjw-s Had the same problem, read the source code. It only looks to the root of /dev, ended up with udev rules as well. :-)

@billimek an interesting thing, looks thicker. I believe there was something similar in RH OCP, maybe even this one.
In any case, something must be done with this common practice of privileged containers.

**Comment by lazyoldbear** [comment]
Another tricky thing I noticed. If devices with the corresponding device numbers already exist in the image (e.g. current zwavejs2mqtt, see the [discussion](https://github.com/zwave-js/zwavejs2mqtt/issues/216)), smarter devices do not appear in the system. But! The already existing devices will still work in unprivileged container. So, it just gives access to the simulated hardware, which is very nice.

I have to admit, however, that node-feature-discovery looks more mature and promising from a brief glance. Have no power to dig it now, but worth comparing.

**Comment by lazyoldbear** [comment]
@billimek This sounds silly, but from looking over the manual and source code, I have not found a way to use NFD to provide access. It does label the nodes, helping create proper affinity, all right. 
But then again, I have one node, which yields very humble (boolean) diversity of node selection options. 
The very problem, on the other hand, is to:

1. Let a pod use the device.
2. Don't let others use that device before this pod is done.

**Comment by candlerb** [comment]
@bjw-s:
> Unfortunately I couldn't get it to work with subpaths (like `/dev/serial/by-id/some-device`) only `/dev/ttyUSB*`, which would be annoying if that means I have to create udev rules to get legible aliases for the devices.

@lazyoldbear:
>  It only looks to the root of /dev

I had a go at patching smarter-device-manager, you can find the diff [here](https://gitlab.com/candlerb/smarter-device-manager/-/tree/candlerb/dev-subdir).  Unfortunately the repo isn't open to issues or pull requests :-(
