### ISSUE TITLE
zwave2mqtt doesn't work on first install

### ISSUE THREAD

**Issue by hwestman** [k8s-at-home/charts#5]
**Setting my configuration in the zwave2mqtt UI, results in exception.**

_Kubernetes version v1.17.0_
Cluster of 3 bare metal nodes running ubuntu server 18.04. Aeotec z-stick gen 5, tested on two different nodes. 

Deploying with 
`helm install --namespace=default zwave2mqtt -f ./helm-configs/zwave2mqtt-values.yaml billimek/zwave2mqtt`

Deploying the helm chart with default values except I have:
- upped the image version to 3.0.2 
- enabled persistence.
- Set affinity for the node with my z-stick
- Added ingress

I can provide zwave2mqtt-values.yaml in full if needed.

**Setting my configurations in the zwave2mqtt UI results in the following log in the container:**
    
    2020-04-04T18:56:23.404Z z2m:Zwave Connecting to /dev/ttyACM0
    2020-04-04 18:56:23.408 Always, OpenZwave Version 1.6-1061-g14f2ba74 Starting Up
    2020-04-04 18:56:23.408 Warning, Unable to load Localization file /usr/local/etc/openzwave/Localization.xml: Failed to open file
    2020-04-04 18:56:23.409 Warning, Exception: Localization.cpp:794 - 1 - Cannot Create Localization Class! - Missing/Invalid Config File?

If I downgraded to 2.2.0 I would get the gateway working, nodes would report values but the gateway would not recognize devices. E.G. Aeotec Siren 6 would show up as "unknown" and would not expose all expected entities. The log would show warnings related to reading xml files.

Could this be related to some missing `securityContext` ? Seems its having issues reading expected configuration that should have been written at some point but perhaps OpenZwave was not allowed to write it? 

The `/usr/local/etc/openzwave/` dir is empty.
I assume  i'm hitting this line in OpenZwave : https://github.com/OpenZWave/open-zwave/blob/e3bae88f29139032c736144b67e7c67d3a764b2b/cpp/src/Localization.cpp#L794

**Comment by carpenike** [comment]
Heh, this bit me today too.
