### ISSUE TITLE
[paperless] consumer pod requires that all PVCs be present

### ISSUE THREAD

**Issue by carpenike** [k8s-at-home/charts#519]
@mr-onion-2 -- would like your thoughts on this!

Looks like the values.yaml calls out the additionalVolume which references the PVs. However, those PVs are not required to run per the above persistence block:

https://github.com/k8s-at-home/charts/blob/master/charts/paperless/values.yaml#L29-L56

Wondering what a good layout would be for storage given that some of these files should likely live on an NFS share that persists rather than PVs that can be volatile.

**Comment by carpenike** [comment]
There's other issues with Paperless -- the startup script chowns / chmods all files in its directories. This works fine if using a PV/PVC, but I'm using NFS shares as that's where my printer scans things to. This won't work (operation not permitted).

Opened an issue here: https://github.com/the-paperless-project/paperless/issues/721

**Comment by mr-onion-2** [comment]
Hi there !

I came across that at the weekend actually when I was troubleshooting trying to get it to work with Longhorn. 

As for a good layout, I'm not sure I have any good input for that, but shall have a ponder

**Comment by carpenike** [comment]
@mr-onion-2 Thanks!

I moved over to Teedy instead. Seems to work nicely.

Helm Chart: https://github.com/k8s-at-home/charts/tree/master/charts/teedy
My Deployment: https://github.com/carpenike/k8s-gitops/blob/master/cluster/default/teedy/teedy.yaml

Need to move the "importer" password to a k8s secret and then use the ValueFrom.Secret option for the additional container.

**Comment by mr-onion-2** [comment]
Very nice! I hadn't seen that, I might have to migrate 😁👍
Thanks

What do you think we should we do with this chart?

**Comment by mr-onion-2** [comment]
So I came across a [fork](https://github.com/jonaswinkler/paperless-ng) of Paperless which has a number of improvements including a shiny new front end and machine learning based tag assignment. It also gets around the consumer pod PVC issue. 

There is a discussion going on over at the project's GitHub regarding whether this should be merged into the core or replace it.

I've updated the current [Paperless chart](https://github.com/mr-onion-2/charts/tree/master/charts/paperless) to support the new fork for now in anticipation that it will be merged..

I've updated the major version so do you think it's fair to just update the chart anyway? I guess if anyone wishes to carry on using the 'old' version they still can.

PS. I tried out Teedy but I couldn't find a multi-arch image of the docs-importer. I didn't spend too much time looking though.

**Comment by bjw-s** [comment]
Is there something else we need to / can do in light of this issue now that #525 has been merged?

**Comment by mr-onion-2** [comment]
Nope, this is not an issue with the new chart
