### ISSUE TITLE
[home-assistant] Questions about home-assistant chart

### ISSUE THREAD

**Issue by markus7811** [k8s-at-home/charts#524]
Hi,

first of all, let me tell you, that i like your work. It's really comfortable to find maintained helm charts for software like unifi and home-assistant.

But ;-)

I was struggling with updating the version i installed in november to the current version of home assistant. Ok, it was a major version upgrade, but it wasn't really clear how to manage it.
At first, everything was fine - home assistant startet, my data was there - some minor functions were not working. But than i migrated vscode to the new values structure - and this deleted my pvc! All data lost ...

It would be nice, if  there would be a documentation on how to upgrade to the next major version without loosing all data :-)

**Comment by Ornias1993** [comment]
Your issue description does not seem to have anything to do with the issue title

**Comment by bjw-s** [comment]
I agree with @Ornias1993, the issue title/description don't really match up.
Also, it seems highly unlikely that the chart removes PVC's. You can check if the original PVC is still there with the `kubectl` tool and if so, refer to that using the `existingClaim` feature of the chart.

**Comment by lazyoldbear** [comment]
Upgrading through deleting and installing might have yielded such outcome. It is a good practice to always `helm upgrade —install`.
However, PVs, albeit persistent in a way, shall not be considered as a robust storage. Specifically, HA configuration is an example where backup is absolutely necessary. 
This can be set up through:

- Blunt committing of all (plenty of examples) to a git repository,
- K8s backup solution (be warned: restic used by velero does not do hostpath, but there is K10 and other things),
- Copying everything to an S3-talking object storage (locally or externally) using a sidecar container.

**Comment by Ornias1993** [comment]
@lazyoldbear I'm quite a fan of duplicati myself, running in its own container with hostPath mounted directories to-backup.
But yes: I personally find PV(c)'s very troublesome for actual configuration on single-container single-node deployments... It's not very user friendly and has it's own set flukes.

Where PV(C)'s shine, is deployments with multiple nodes running HA containers. Where containers sync their own data and as such each individual PV(C) isn't really important

**Comment by lazyoldbear** [comment]
I would advise against deployments and persistency. StatefulSet was called stateful not only because it is a set.

**Comment by Ornias1993** [comment]
I was using the term deployment more liberally than defining just deployments.
