### ISSUE TITLE
Node red doesn't work with persistence enabled

### ISSUE THREAD

**Issue by iMartyn** [k8s-at-home/charts#537]
# Details

**Helm chart name and version:**

node-red:5.3.1

**Container name and tag:**

nodered/node-red:1.2.5

**What steps did you take and what happened:**

enabled persistence using the wacky library parameters :
```
persistence:
  data:
    accessMode: ReadWriteOnce
    size: 1Gi
    enabled: true
```
Nodered crashloops because it is not able to write to the pvc because of permission errors :
```
> node-red-docker@1.2.5 start /usr/src/node-red
> node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"

fs.js:114
    throw err;
    ^

Error: EACCES: permission denied, copyfile '/usr/src/node-red/node_modules/node-red/settings.js' -> '/data/settings.js'
    at Object.copyFileSync (fs.js:1728:3)
    at copyFile (/usr/src/node-red/node_modules/fs-extra/lib/copy-sync/copy-sync.js:68:8)
    at onFile (/usr/src/node-red/node_modules/fs-extra/lib/copy-sync/copy-sync.js:53:25)
    at getStats (/usr/src/node-red/node_modules/fs-extra/lib/copy-sync/copy-sync.js:48:44)
    at startCopy (/usr/src/node-red/node_modules/fs-extra/lib/copy-sync/copy-sync.js:38:10)
    at handleFilterAndCopy (/usr/src/node-red/node_modules/fs-extra/lib/copy-sync/copy-sync.js:33:10)
    at Object.copySync (/usr/src/node-red/node_modules/fs-extra/lib/copy-sync/copy-sync.js:26:10)
    at Object.<anonymous> (/usr/src/node-red/node_modules/node-red/red.js:125:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-red-docker@1.2.5 start: `node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-red-docker@1.2.5 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**What did you expect to happen:**

Nodered would start up

**Anything else you would like to add:**

Probably will need to allow non-root users to write to the pvc with permissions flags that just don't exist in the templates right now.

**Additional Information:**

It would be really nice to not have to dig in multiple templates to find the source of these kind of errors.  

Side note: Try installing the helm charts in argocd - you will see that the lack of information in the direct `values.yaml` causes you not to be able to use the UI at all to enter 90% of the values.  Perhaps you could have CI create the `values.yaml` for each chart rather than having such minimal `values.yaml` files in the actual charts.

**Comment by onedr0p** [comment]
Hi @iMartyn I  have been using this chart for awhile, and have no issues with persistence. What is your underlying storage? I am using rook-ceph (and used longhorn in the past) without any problems...

Maybe you are running into issues with the Docker image? e.g.
https://nodered.org/docs/getting-started/docker#using-a-host-directory-for-persistence-bind-mount

**Comment by iMartyn** [comment]
I'm using longhorn PVCs, and they default to `root:root`.

Because of the assumptions made by the chart, `fsGroup` can't be added to `values.PodSecurityContext` as it applies it to the `container:` level which isn't valid.  See https://github.com/helm/charts/issues/11351 for a discussion of this.  It must be applied _only_ at the pod level not container.  From what I can tell, if you add it to the values at the top level, it adds it in both places.

On ArgoCD, it provides "parameters" by scanning the values file.  Given that the values file is intentionally bare, there's no UI input for 90% of the values.  Here's a screenshot for you to see the UI and how bare the customisation is with the bare values.yaml.
![image](https://user-images.githubusercontent.com/962908/106807791-dbca4e80-6669-11eb-8ef4-2155b8f6545c.png)
Making sure the customisations are available in the base `values.yaml` file is key here, but I suggested CI for the fact that the abstraction you're using is so heavy.

For reference, I've been working with helm as {platforrm engineer/devops/sre/job title of the week} for the past 4-5 years and this library stuff you're using is frustrating as hell to debug.  Sure it might be nice when it's working but when it breaks because you make assumptions that don't work on other peoples' systems, it's almost impossible to debug.  Indirection on indirection and hours of debugging to find out why the chart doesn't work.

**Comment by onedr0p** [comment]
> Because of the assumptions made by the chart, `fsGroup` can't be added to `values.PodSecurityContext` as it applies it to the `container:` level which isn't valid. See [helm/charts#11351](https://github.com/helm/charts/issues/11351) for a discussion of this. It must be applied _only_ at the pod level not container. From what I can tell, if you add it to the values at the top level, it adds it in both places.

Unless I am missing something, according to the [Kubernetes docs](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod), `fsGroup` will work in the common library where we have [pod defined](https://github.com/k8s-at-home/charts/blob/master/charts/common/templates/lib/controller/_pod.tpl#L11).

> On ArgoCD, it provides "parameters" by scanning the values file. Given that the values file is intentionally bare, there's no UI input for 90% of the values. Here's a screenshot for you to see the UI and how bare the customisation is with the bare values.yaml.

There is no way you can commit your chart releases as code and have Argo pick up on it instead of using a UI? Isn't that one of the main purposes of GitOps, to drive your cluster state from a Git repo, not a custom built UI?

> Making sure the customisations are available in the base `values.yaml` file is key here, but I suggested CI for the fact that the abstraction you're using is so heavy.

> For reference, I've been working with helm as {platforrm engineer/devops/sre/job title of the week} for the past 4-5 years and this library stuff you're using is frustrating as hell to debug. Sure it might be nice when it's working but when it breaks because you make assumptions that don't work on other peoples' systems, it's almost impossible to debug. Indirection on indirection and hours of debugging to find out why the chart doesn't work.

The way we built the common library was to keep things as DRY as possible, there is soo much duplication of code between all the charts that maintaining consistency between application charts was becoming a true nightmare. It's true that there is some small learning to be had when using a chart that implements our common library.

**Comment by iMartyn** [comment]
> Unless I am missing something, according to the Kubernetes docs, securityContext and podSecurityContext will work in the common library where we have container and pod respectively defined.

The problem comes with this :
```{{- with .Values.securityContext }}```

that you are treating `pod.securityContext` and `container.securityContext` as the same.  They're not, as discussed in the `helm/charts` issue I mentioned.  Yes, the k8s documentation doesn't really make that clear, as is also mentioned in the same issue.

> There is no way you can commit your chart releases as code and have Argo pick up on it instead of using a UI? Isn't that one of the main purposes of GitOps, to drive your cluster state from a Git repo, not a custom built UI provided by Argo?

yes, and no, here is the thing, Argo is both a UI to releases and a gitops solution.  If you know exactly the values, you can also paste them in, but that's not the point I was making.  Let me try and describe it differently.  To me `values.yaml` in itself is a form of documentation.  This is also clear in the old helm charts repo where the `values.yaml` was parsed into a nice table and comments added in addition to the default value.  By not even listing `accessMode` and `size` in the values, you have to go digging to find out what they should be.  In addition to the lack of intuitive and not really documented (at least from the perspective of the single chart that the user is looking at) way of knowing is it `persistence.config` or `persistence.data` or what.  Helm is inherantly flexible so there is no way of making it intuitive, so it does need documenting, and `values.yaml` is itself a form of documentation.

> What's better, one place to implement a change or 60+ places? The way we built the common library was to keep things as DRY as possible, there is soo much duplication of code between all the charts that maintaining consistency between application charts was becoming real problem. It's true that there is some small learning to be had when using a chart that implements our common library or developing a new chart.

I would argue that this depends entirely on perspective.  Sure, it's easier for you, but absolutely isn't easier for me as a user who wants to fill in some values and have a working installation (without having to debug the templates to figure out what the heck is going on so I can fill in the values!).  Some of the library stuff now is making it that you are (in my view needlessly) exposing the kubernetes internals to a level where I'm finding myself questioning the worth of having it as a helm chart at all.

> We're open to suggestions for improvements and love contributions from the community.. especially around documentation.

I'm limiting myself to contributing by reporting this issue and discussing it.  I am only doing this because this is the final resting place of the "official" node-red chart.  tbh, I would rather start from scratch and provide a helm chart myself that doesn't use this kind of "treat every appplication the same, and expose the k8s stuff if you need to run it in a way that differs" approach than become a "contributor" to this repo.

For clarity, to me, the whole point of having a helm chart is that it _is_ customized to the application.  If I have to debug some library and still have to write k8s yaml to make it do basic stuff, like have working storage permissions, then I may as well treat the chart as nonexistant and write one from scratch.

I feel by taking this chart into this repo and forcing it into your own library structure, that doesn't work for a fairly standard use-case, it's a disservice to it, especially as when you go to the official helm charts repo and follow the "don't use, it moved here" chain, you effectively are the official and only supported chart for this application.

I don't expect you to change it, because you have clearly invested a lot of time into the library, but hopefully my words have helped you understand my perspective and if not, well at least you have the bug report.

**Comment by onedr0p** [comment]
> The problem comes with this :
> `{{- with .Values.securityContext }}`
> 
> that you are treating `pod.securityContext` and `container.securityContext` as the same. They're not, as discussed in the `helm/charts` issue I mentioned. `fsGroup` statements are only allowed on the `pod` level and not the `container` level. Yes, the k8s documentation doesn't really make that clear, but then the docs site rework doesn't help that with it's lovely array of broken deeplinks.

I was trying to correct my previous statement, to be clear our charts using the common library allows for setting both `.Values.securityContext` AND `.Values.podSecurityContext`. E.g. it is entirely possible to:

```yaml
securityContext:
  runAsUser: 1000
  runAsGroup: 1000
```

and/or

```yaml
podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
```

If you are trying to point out this doesn't work, please explain in a bit more detail your problem. We can fix it.

> yes, and no, here is the thing, Argo is both a UI to releases and a gitops solution. If you know exactly the values, you can also paste them in, but that's not the point I was making. Let me try and describe it differently. To me `values.yaml` in itself is a form of documentation. This is also clear in the old helm charts repo where the `values.yaml` was parsed into a nice table and comments added in addition to the default value. By not even listing `accessMode` and `size` in the values, you have to go digging to find out what they should be. In addition to the lack of intuitive and not really documented (at least from the perspective of the single chart that the user is looking at) way of knowing is it `persistence.config` or `persistence.data` or what. Helm is inherantly flexible so there is no way of making it intuitive, so it does need documenting, and `values.yaml` is itself a form of documentation.

It might be worth opening an issue or submitting a PR to the ArgoCD project for allowing them to pull in `values.yaml` for any charts listed as a dependency in the app charts `Chart.yaml`. Your complaints seem more about ArgoCD not supporting configuring `values.yaml` from dependencies. This would also be the same as an application chart having a dependency on any chart like `postgres`, `mariadb` or whatever. The values of an app charts' dependency would not be included in ArgoCD's UI.

> I would argue that this depends entirely on perspective. Sure, it's easier for you, but absolutely isn't easier for me as a user who wants to fill in some values and have a working installation (without having to debug the templates to figure out what the heck is going on so I can fill in the values!). Some of the library stuff now is making it that you are (in my view needlessly) exposing the kubernetes internals to a level where I'm finding myself questioning the worth of having it as a helm chart at all.

We get there is documentation that needs to be improved upon. As of now, for new people coming in here we try to familiarize them with the `values.yaml` in the common library and once they realize that they seem to like the pattern. But obviously I cannot speak for everyone in the community.

> For clarity, to me, the whole point of having a helm chart is that it is customized to the application. If I have to debug some library and still have to write k8s yaml to make it do basic stuff, like have working storage permissions, then I may as well treat the chart as nonexistant and write one from scratch.

Maybe we need to describe our goals of this repo a bit more clearly. We are not aiming to be an enterprise helm chart repo. Our charts are for people who have deployed Kubernetes at home, making it easy for them to do so, and to support charts that are only deployed at home.

It just so happens to be that A LOT of charts are very similar in structure, take a look at `sonarr`, `radarr`, `nzbget`, and many others. For the most part all they need is to allow very few customization, like a `port`, `persistence`, `ingress` and `image`, that's all. There is nothing else for the majority of these charts that need other configuration that isn't covered in the common library and when the common library doesn't support it, we're sad about going against the grain.

We're only a community doing this in our free time, and don't have the full CI or time to dedicate to opening PRs across all these charts when a new feature needs to be added a chart, thus making us open PRs for other charts to support the same feature.

> I feel by taking this chart into this repo and forcing it into your own library structure, that doesn't work for a fairly standard use-case, it's a disservice to it, especially as when you go to the official helm charts repo and follow the "don't use, it moved here" chain, you effectively are the official and only supported chart for this application.

I cannot stress enough that we are in no way official helm charts for any of these applications. We try our best to encourage the application developers to support their own charts when they have the thirst for it (even going as far as [helping them set it up](https://github.com/blakeblackshear/blakeshome-charts/pull/1)) and deprecate our own in place of theirs.
