### ISSUE TITLE
[dashmachine] Remove dashmachine or change to fork

### ISSUE THREAD

**Issue by Ornias1993** [k8s-at-home/charts#545]
Considering the steady increase of issues, a huge backlog of PR's without any activity and no commits for months: 
This project is clear vaporware/abandonware.
The consequences are potential security risks.

There are also great viable alternatives to this, like Heimdall or Organizr.

Taking into account this is already a VERY niche application: Either the used container needs to be changed to an active fork, or the application needs to be removed.

**Comment by carpenike** [comment]
I would agree. If the upstream developers are no longer building the app it makes sense to deprecate / remove.
