### ISSUE TITLE
[common] PVC volumeName/selector

### ISSUE THREAD

**Issue by tmager** [k8s-at-home/charts#556]
# Details

**Helm chart name:** `common`
**Describe the solution you'd like:**
At present these doesn't appear to be a way to bind PVCs created by the `common` chart to specific existing PVs or subsets of PVs.  It would be nice to expose the PVCs' `volumeName` and/or `selector` attributes through the chart's values.

**Anything else you would like to add:**
I would be willing to implement this if the maintainers are on board, but might not get around to it for a while.

**Comment by carpenike** [comment]
Hi @tmager! Something like this? https://github.com/carpenike/k8s-gitops/blob/master/cluster/default/home-assistant/home-assistant.yaml#L27-L30

**Comment by tmager** [comment]
Hey @carpenike -- I could get around this by creating the PVCs beforehand and using `existingClaim`, but letting the chart handle it seems like a more straightforward approach.  I'm not doing dynamic provisioning at the moment, just manually setting up a few PVs; definitely not aiming for something super-complicated.  Looking through that repo, your setup is awesome -- I just don't have that kind of time.

I was mostly just testing the water to see if this is something that anyone actually thinks would be useful; if not I'll probably do as you suggest.

**Comment by bjw-s** [comment]
I feel that the best-practice way to handle this is by using existingClaims. I don't think any of the "major" chart providers add these selectors either.

**Comment by tmager** [comment]
Bitnami does, but your point still stands.  Sounds like this can just be closed, then.
