### ISSUE TITLE
zigbee2mqtt - can't create '/data/configuration.yaml'

### ISSUE THREAD

**Issue by tibbon** [k8s-at-home/charts#559]
# Details

**Helm chart name and version:**

zigbee2mqtt:latest

**Container name and tag:**

koenkk/zigbee2mqtt:1.17.0

**What steps did you take and what happened:**

```
$ helm install my-mqtt k8s-at-home/zigbee2mqtt

$ kubectl get pods
NAME                                         READY   STATUS             RESTARTS   AGE
my-mqtt-zigbee2mqtt-94fd6dff-kjmz6           0/1     CrashLoopBackOff   9          23m

$ kubectl logs my-mqtt-zigbee2mqtt-94fd6dff-kjmz6
Using '/data' as data directory
Creating configuration file...
cp: can't create '/data/configuration.yaml': No such file or directory
```

**What did you expect to happen:**

The configuration to create, and the pod/deployment to launch

**Anything else you would like to add:**

On k3s on Raspberry Pi 4.

**Comment by onedr0p** [comment]
Would you like to share your `values.yaml`?

**Comment by tibbon** [comment]
Oh, I think I let it use the default values, and didn't pass any in.

**Comment by onedr0p** [comment]
Yes, you need to configure and read carefully thru the charts `values.yaml`

**Comment by tibbon** [comment]
Thanks! I think I was thrown off by the instructions not showing `-f values.yaml` as a requirement for it to work.

**Comment by onedr0p** [comment]
Are you good here @tibbon, you need enable `persistence` to set it to something
