### ISSUE TITLE
Plex - Does not work on Raspberry Pi 4 with k3s

### ISSUE THREAD

**Issue by tibbon** [k8s-at-home/charts#560]
# Details

**Helm chart name and version:**

`plex:latest`

**Container name and tag:**

`plexinc/pms-docker:1.20.2.3402-0fec14d92`

**What steps did you take and what happened:**

```
$ helm install plex k8s-at-home/plex

$ kubectl get pods
NAME                                         READY   STATUS              RESTARTS   AGE
plex-6c85dc9d77-24njs                        0/1     CrashLoopBackOff   2          2m14s

$ kubectl logs plex-6c85dc9d77-24njs
standard_init_linux.go:211: exec user process caused "exec format error"
```

**What did you expect to happen:**

Plex to run, no error

**Anything else you would like to add:**

I'm guessing the container isn't build for arm7? Nothing in the documentation indicates this wouldn't be expected to work.

**Comment by onedr0p** [comment]
This is not an issue with the charts, the official plex images do not support multi-arch:

https://hub.docker.com/r/plexinc/pms-docker/

You might want to use the lsio images instead:

https://hub.docker.com/r/linuxserver/plex/

**Comment by tibbon** [comment]
How would someone know from looking at these charts to expect it to not work? Could we amend the documentation?

**Comment by onedr0p** [comment]
Yes, please open a PR if you want to clarify this. 

However doing a little amount of investigation would bring you to realize that the official Plex container images are not multi-arch and also, searching thru the issues here would have found you [this issue](https://github.com/k8s-at-home/charts/issues/16)
