### ISSUE TITLE
add new chart for steamcmd

### ISSUE THREAD

**Issue by crutonjohn** [k8s-at-home/charts#561]
# Details

**Helm chart name:**
steamcmd

**Describe the solution you'd like:**
implement a chart that can deploy steamcmd resources to cluster, remaining game agnostic. this would allow anyone to use steamcmd to host game servers that are supported by steamcmd.

i'm open to tackling this myself. this issue can just be for tracking.

**Anything else you would like to add:**
due to limitations with game hosting, this may not qualify for using a multi-arch image. i'll defer to the multi-arch powers that be for supporting that use case.

**Additional Information:**

see the steamcmd project here: https://github.com/steamcmd/docker

**Comment by onedr0p** [comment]
This looks juicy

**Comment by crutonjohn** [comment]
the farther i'm getting into this, the more i'm realizing why nobody has done it yet

**Comment by crutonjohn** [comment]
work is being performed in https://github.com/crutonjohn/charts/tree/add-chart-steamcmd

just gave it my initial commit

**Comment by Ornias1993** [comment]
I've a different idea about this...
A lot of gameservers don't just use steamcmd and require additional tools.

Why not integrate SteamCMD into the common chart, just like some other addons?

That way people could start building gameservers using the common chart and attach the addon for steamCMD to streamline the process.

**Comment by crutonjohn** [comment]
> I've a different idea about this...
> A lot of gameservers don't just use steamcmd and require additional tools.
> 
> Why not integrate SteamCMD into the common chart, just like some other addons?
> 
> That way people could start building gameservers using the common chart and attach the addon for steamCMD to streamline the process.

ultimately, i'm not sure what's best.

if you approach it from the standpoint that it is like an add-on, you take on the burden of trying to "standardize" (for lack of a better term) lots of other varying game server types.

the one nice thing about steamcmd is that it's already an established platform that is meant for running and updating Steam dedicated servers. there's no guarantee that whatever we come up with as a solution would be extensible to, or compatible with, other game server types.

i'm all for supporting as many use cases as possible, but extending the functionality of this chart to be a catch-all for _any_ type of game server seems like a bit of a stretch.

**Comment by Ornias1993** [comment]
Almost every decent gameserver uses a server manager AND steam CMD, not just steamcmd. Als by adding steamcmd as a common chart addon you are making it possible to customise. Your solution is the one thats hard to customise.

i dont think you understand what I meant with addon and common chart. Please read into it.

**Comment by crutonjohn** [comment]
Taking the holiday break to work through this 😬
