### ISSUE TITLE
[couchpatato] deprecate and remove CouchPatato

### ISSUE THREAD

**Issue by Ornias1993** [k8s-at-home/charts#563]
# Details
CouchPatato has been abandonware for years now.
I tried to track why it actually got added last year as a chart, but due to all restructuring git wasn't happy about it. It does show there needs to be more quality vetting of the underlaying applications behind charts.

Running years old webui's on python and such, is a very bad idea and shouldn't be supported in any way, shape or form (besides completely forking couchpatato)

**Helm chart name:**
couchpatato

**Describe the solution you'd like:**
Preferably someone moves the chart to a fork or forks the couchpatato project.

If thats not to happen:
At the very least the chart needs to be deprecated.
either directly, or in the long run, followed by complete removal

**Anything else you would like to add:**
To be clear: i don't want to be "that guy" when it comes to deprication and deleting charts, but there has to be some line drawn in the sand. 
No mater where you place that line: years of inactivity would almost always cross it, leading to deprecation/removal

**Additional Information:**

**Comment by onedr0p** [comment]
I am actually okay with this, not only is the app in a unsupported state in terms of commits but the maintainer has shut off every area of people asking for support. GH issues on the repo are disabled and he closed down the couchpotato forums about 6-8 months ago.

**Comment by Ornias1993** [comment]
Yeah, not a fan of cutting this as we all have a history with this project.
But... yeah...  i'll look into it this week!
