### ISSUE TITLE
[mosquitto] Move mosquitto to Common chart

### ISSUE THREAD

**Issue by Ornias1993** [k8s-at-home/charts#565]
# Details
mosquitto seems to be a pretty light-weight and simple chart, that could easily be integrated with the common chart.

**Helm chart name:**
mosquitto

**Describe the solution you'd like:**
Common Chart integration

**Anything else you would like to add:**
Mostly for reference and reminder, not expecting it to happen tomorrow.

**Additional Information:**

**Comment by ishioni** [comment]
I don't have a way to mount configmaps with release-generated names in values.yaml in common. Mosquitto 1.x will run okayish without one (though persistence is off the table), but 2.x is out of the question as it's secure-by-default

**Comment by Ornias1993** [comment]
@ishioni I get it... That might actually require a change in common to allow something like "config-tpl" (as we also have for envtpl)

**Comment by ishioni** [comment]
I've already figured out the method in transmission, so expect one in the coming days

**Comment by Ornias1993** [comment]
@ishioni awesome! :)

**Comment by ishioni** [comment]
@Ornias1993 monitor #626
