### ISSUE TITLE
[common] New probe settings are aggressive for constrained systems

### ISSUE THREAD

**Issue by turnrye** [k8s-at-home/charts#589]
# Details

**Helm chart name and version:**

Common 3

**Container name and tag:**

e.g. sonarr, lidarr, radarr

**What steps did you take and what happened:**

Recently, Sonarr was updated to use common v3. This is great! Except in moving the probes to more aggressive times, it has a frustrating side effect.... containers were exited due to the checks before they finished bootstrapping.  For example, check [this gist](https://gist.github.com/turnrye/4acee204c5ad11e3950bca1495f60bcb).

**Relevant Helm values:**

**What did you expect to happen:**

I expected to be able to start the container

**Anything else you would like to add:**

My advice is that we need to document this some place obvious. I understand the desire to get consistency and help startup times. For the uninitiated though this could be a frustrating problem to troubleshoot since the logs just show the pod quitting and without understanding how these particular images work, you might misunderstand the probe failure logs for some other issue.

**Additional Information:**

**Comment by carpenike** [comment]
Maybe we override the defaults in the chart specific values.yaml when we know it requires more time?

**Comment by onedr0p** [comment]
The default for the start up prode is 150 seconds before the pod is killed, did you notice how long it took after bumping the probe values?

**Comment by onedr0p** [comment]
I honestly think what we have a sane defaults for applications. Why does Sonarr take more than 2m30s to become ready for you @turnrye ?

**Comment by turnrye** [comment]
@onedr0p I think I had a corner case. I migrated an old installation over and was consolidating to a new cluster that was resource constrained. I’ll self close this. Maybe the keywords are helpful to someone in the future in case they see unexplained startup failures :)
