### ISSUE TITLE
Error: chart requires kubeVersion: >=1.16.0 which is incompatible with Kubernetes v1.20.1-34+e7db93d188d0d1

### ISSUE THREAD

**Issue by benalexau** [k8s-at-home/charts#590]
# Details

I have a microk8s test environment tracking the `1.20/stable` channel. 

Attempting to install k8s-at-home charts which have been upgraded to Common 3 now fails. For example:

```$ helm install zwave2mqtt k8s-at-home/zwave2mqtt --version 7.0.0
Error: chart requires kubeVersion: >=1.16.0 which is incompatible with Kubernetes v1.20.1-34+e7db93d188d0d1
```

**Additional Information:**

PR #582 added `kubeVersion: ">=1.16.0"` to most charts.

PR #572 suggested adding `kubeVersion: ">=1.16.0-0"`.

https://github.com/helm/helm/issues/3810 describes the impact of the suffix.

**Comment by bjw-s** [comment]
Yikes, that is not great... I noticed @billimek suggesting `>=1.16.0-0` but went with `>=1.16.0` since according to semver everything after the hyphen is supposed to be a pre-release tag. I will create a bugfix for this somewhere today 👍
