### ISSUE TITLE
[common] Unit tests not happy when adding pre-install Jobs

### ISSUE THREAD

**Issue by Ornias1993** [k8s-at-home/charts#597]
# Details
**Helm chart name and version:**

common, 3.0.1

**What steps did you take and what happened:**

- Add a pre-install container (just a wait of 5 seconds) to the common chart
- Notice the unit tests fail

**Relevant Helm values:**

Super clean pre-install container, just hostpath mounts, labels and:
```
        - name: set-mount-permissions
          image: "alpine:3.3"
          command: ["/bin/sleep","5"]

```
**What did you expect to happen:**
I expect no issues with the common unit tests

**Anything else you would like to add:**

While I expect there may have been some interferance with the unittest (it's another container ofc.), the problem is that the unittests freaks out all over the board. It looks like the tests reads the pre-install pod's templates and nothing more or something

**Additional Information:**

While this is not relevant for k8s directly (and thus a low-priority bug), it does showcase some possible future issues with regards to the way unit-testing is done in general

**Comment by onedr0p** [comment]
Why are you adding that init-container to the common library in the first place? SHouldn't that go in the application chart that consumes it?

**Comment by Ornias1993** [comment]
I'm not talking about init containers, i'm talking about pre-install jobs, there's a difference

**Comment by onedr0p** [comment]
Can you add more context (code) to your snippet? I am really unsure where you are referencing it from.

**Comment by Ornias1993** [comment]
@onedr0p it's just to explain that the pre-install job doesn't run anything relevant.
I have the feeling you have no idea what a Helm pre-install job is... do you? :s

**Comment by onedr0p** [comment]
It's a helm hook, but I am still confused how it is affecting the unit tests? The unit test only cover the common library...

**Comment by bjw-s** [comment]
> @onedr0p it's just to explain that the pre-install job doesn't run anything relevant.
> I have the feeling you have no idea what a Helm pre-install job is... do you? :s

You commented recently that you did not appreciate being spoken to in a certain manner. I feel a similar comment from us could be made here. Let's try to keep things cordial.

**Comment by Ornias1993** [comment]
> It's a helm hook, but I am still confused how it is affecting the unit tests? Can you open a PR with what you are trying to do or add more context (code and debug output)?

Did you try adding a job, with a pre-install hook?
I think my reproduction guide is quite solid.

**Comment by Ornias1993** [comment]
After 3 days of deep diving into ruby, I know the limits of the test suite.
Closing because this is not really the issue, always picking the first resource is and has much wider implications.
