### ISSUE TITLE
[common] handle volume configmaps/secrets

### ISSUE THREAD

**Issue by ishioni** [k8s-at-home/charts#607]
# Details

**Helm chart name:**
common

**Describe the solution you'd like:**
I need something like
```yaml
volumeFromConfigMap:
  nameSuffix: config
  data: |
    whatever
```
Or a way to be able to compute release names in additionalVolumes. In transmission this is only a minor nuisance, but stuff like mosquitto 2.x or icantbelieveitsnotvaletudo can't move to common, because they can't work without a config file. 

**Anything else you would like to add:**
In my charts i try to make the config present itself as yaml and then try to process it into the target format ( with toJson for example ). It would be great if I could keeo doing that, but have absolutely no idea how to make that happen :(

**Additional Information:**

**Comment by bjw-s** [comment]
Hi, thanks for raising this issue. 

Currently what you wish to accomplish is already possible through the features of the common library. For example, the [Zigbee2MQTT](https://github.com/k8s-at-home/charts/tree/master/charts/zigbee2mqtt/templates) chart already does something like this.

Could you let us know if this approach would work for you?

**Comment by ishioni** [comment]
Yes! This is exactly what I was looking for :) You can close this

**Comment by bjw-s** [comment]
Cool! Great that that would work :) I'll leave the issue open for now as a reminder for me to add some documentation about this to the wiki.

**Comment by bjw-s** [comment]
I've added this example to the wiki: https://github.com/k8s-at-home/charts/wiki/Common-library:-Creating-a-new-chart
