### ISSUE TITLE
[home-assistant] Support existingSecret for git.deployKeyBase64

### ISSUE THREAD

**Issue by carpenike** [k8s-at-home/charts#632]
This is the last remaining secret that I need to maintain a helm-values file for.

**Comment by bjw-s** [comment]
We're actively working on moving this over to the codeserver addon in the common chart. (https://github.com/k8s-at-home/library-charts/issues/23)

**Comment by bjw-s** [comment]
This is now available in the latest common library. Once https://github.com/k8s-at-home/charts/pull/801 is merged, it will be removed from the Home Assistant chart
