### ISSUE TITLE
[Wiki] Wiki not git compatible

### ISSUE THREAD

**Issue by Ornias1993** [k8s-at-home/charts#638]
# Details

I tried to clone the wiki using git, this is a more efficient way of editing than using the web editor. (as it can be edited like any other git repository)

Sadly enough, some of the files where added in ways that are incompatible with git cloning. They got added to a fake folder, which gets cloned as a file.

Git does recognise there are files inside the fake "file"/"folder", but it ofcoarse freaks out completely because it's no folder.

As the "file"/"folder" is called `Common-library`, I think the culprid is the use of this `:-` in the URL, as the `-` is reserved for namespacing (which seems to be what the fake "file"/"folder" represents) as in `{namespace}-{page}`.

##### How to solve this

- Remove any use of `:-`
- If that doesn't work, manually copy all files to project root using GIT.

##### Notes

It's important to note that folder structure is _NOT_ relevant for github wiki's, all files rendered as if they where inside the root of the wiki.

**Comment by bjw-s** [comment]
The project maintainers manually update the wiki through the web editor, so there is no issue for us.
There are some plans to move to another documentation solution, but those are not finalised yet.

**Comment by Ornias1993** [comment]
@bjw-s I think you understand me wrong, as i'm not asking for another documentation solution at all...

It's not "normal" git or some special solution using it, one can also checkout the actual wiki itself (top right corner contains the git url).
But the filenames are causing it to break.

**Comment by onedr0p** [comment]
We're planning on moving the wiki to our docs repo and host it on github pages at https://docs.k8s-at-home.com

**Comment by Ornias1993** [comment]
@onedr0p Ahh same design I currently use for TrueCharts, works great.
But then I get why this is a non-issue, as it's going away anyway it's not worth fixing indeed :)
