### ISSUE TITLE
[Legal] Include Apache NOTICE file

### ISSUE THREAD

**Issue by Ornias1993** [k8s-at-home/charts#639]
# Details

The `NOTICE` file is a quite relevant for APACHE licenced projects, as those notices are required by licence to be included in anyone consuming the code downstream.

**Comment by bjw-s** [comment]
As per the official docs (https://www.apache.org/licenses/LICENSE-2.0#apply) it seems that a `NOTICE` file is optional, it's [only required for Apache projects](http://www.apache.org/legal/src-headers.html#notice).

**Comment by Ornias1993** [comment]
Yes it's optional, but at least having the file is quite relevant and helps people downstreaming correct attribution.
It would nicely trickly-down the attribution from upstream to downstream.

While it's often requested to attribute the upstream project if downstreaming k8s-at-home, the notice file would be the standardised way of doing so within Apach 2.0

**Comment by bjw-s** [comment]
> While it's often requested to attribute the upstream project if downstreaming k8s-at-home, the notice file would be the standardised way of doing so within Apach 2.0

Something like that would not really work when people "take inspiration" from for example our wiki and "forget" to add proper attribution links.

I do agree it could be a useful addition to the code repos. We'll take this under consideration.

**Comment by Ornias1993** [comment]
NOTICE files are at least enforcable attribution in most cases, thats at least something :)
But good to know it's on the radar :)

**Comment by Ornias1993** [comment]
Also:
A short copyright header on all files might be "nice to have" for downstreams.
Because downstreams are *required* by the license to add a header to all files containging any modified apache2.0 licensed content.

If you integrate Apache2.0 code into a BSD project, it's a nice way to somewhat ensure which files originally came from a apache2.0 project.

Simply put:
I could downstream common and write an additional addon under BSD2.
after 5 years and 10 more addons under different licenses, it gets hard to differentiate which files where originally Apache2.0, which is relevant because those files require modification headers after being modified.
