### ISSUE TITLE
[helm-docs] improve method of generating helm-docs

### ISSUE THREAD

**Issue by rolfberkenbosch** [k8s-at-home/charts#665]
Quick question, why is helm-docs not been used in the ci pipeline while the changes are beeing merged ?

**Comment by onedr0p** [comment]
Not sure what you mean, the question you have in the issue title seems to contradict the question in the issue.

**Comment by rolfberkenbosch** [comment]
Sorry, maybe i was not clear enough, my appologies. I mean i have seen that there are templates files for helm-docs intergration exist in the repo. So i was expecting that in the .gitlab/webhooks there is a job that auto generate the readme.md file when the commit is merged into the master/main branch.

**Comment by onedr0p** [comment]
There's currently an issue that prevents us from doing that. Any time a pushed is made that doesn't bump the helm chart version (meta readme updates) it breaks future releases of any chart. The tools we use don't support it. We've been discussing about the best way to handle it.

**Comment by angelnu** [comment]
@rolfberkenbosch - I looked for an option to automatically update the PR to ensure the documentation is updated before merging. I could not find any existing action that would do that (it would involve writing back to the fork originating the WebHook). If you can find of a good way let us discuss here or in Discord.

@onedr0p - what we "could" do is to add a check that helm-docs would not need do any change while checking the PR. This would expect the caller having called helm-docs either with the task or activating the CI helm-docs prior to the PR.

**Comment by stecky** [comment]
@onedr0p can you provide more details about how a push without bumping the chart version "breaks future releases of any chart"?

**Comment by onedr0p** [comment]
> @onedr0p can you provide more details about how a push without bumping the chart version "breaks future releases of any chart"?

This is not the case anymore, we've since updated the workflows that caused that behavior

**Comment by bjw-s** [comment]
#974 would make it easier to auto-generate the README files as well :) In it's current form it will do the README generation in the PR.

Alternatively we could have it (also) run before the Chart Releaser action runs in our master branch, but I kind of like the idea that all code modifications now happen in a branch before they hit master.

**Comment by onedr0p** [comment]
We can close this, #974 was merged 🎉
