### ISSUE TITLE
node-red charts : issue in pvc evaluation

### ISSUE THREAD

**Issue by ronny35** [k8s-at-home/charts#677]
Hello,

I am using node-red chart (version 6.2.0) and, during installation, I have this issue :
`Error: template: node-red/templates/common.yaml:1:3: executing "node-red/templates/common.yaml" at <include "common.all" .>: error calling include: template: node-red/charts/common/templates/_all.tpl:19:6: executing "common.all" at <include "common.pvc" .>: error calling include: template: node-red/charts/common/templates/_pvc.tpl:8:19: executing "common.pvc" at <$PVC.enabled>: can't evaluate field enabled in type interface {}`

In my values.yaml, 
```
persistence:
  enabled: true
```

Could you please inform me why I obtain this error ?

Thanks in advane for your help

**Comment by bjw-s** [comment]
Make sure you set your values according to the chart's `values.yaml` file: https://github.com/k8s-at-home/charts/blob/6a48d3fdb0a865a7bca144174b9ebae7575abadf/charts/node-red/values.yaml#L32-L34

You are missing where you specify which PVC you want to create.

**Comment by ronny35** [comment]
Thanks a lot! Sorry for my misunderstanding :)

**Comment by bjw-s** [comment]
No problem at all, glad it's working for you now 🙂
