### ISSUE TITLE
[plex] TLS configuration and environment variables broken

### ISSUE THREAD

**Issue by acjohnson** [k8s-at-home/charts#713]
# Details
```
NAME                         	CHART VERSION	APP VERSION           	DESCRIPTION                                       
k8s-at-home/plex             	4.0.1        	v1.22.0.4163-d8c4875dd	Plex Media Server    
```
It looks like #698 dropped these scripts that set up environment variables that change important config values in `Preferences.xml` but also the pkcsMangler stuff is broken now as well and is unusable for anyone who uses pkcs#12 formatted TLS certificates with Plex...

[plex/configs/41-plex-preferences](https://github.com/k8s-at-home/charts/pull/698/files#diff-009e23956f0975a9ad382b740ec316527e0eb5c2640ab0fc54fe6cd91f85c1fa)
[plex/configs/42-pkcs-mangler]()

**Comment by onedr0p** [comment]
@acjohnson couple notes here and we're bad about getting this information across:

The chart was upgraded to use our [common library](https://github.com/k8s-at-home/library-charts). 

We have our own kah flavor Plex image available to use which is default in the new chart. The script for custom env was added their to reduce complexity in the chart.

You can read about using our images in our [docs](https://docs.k8s-at-home.com/) and at the repo [here](https://github.com/k8s-at-home/container-images)

For the SSL part, we're you terminating SSL at Plex? If so check out [this issue](https://github.com/k8s-at-home/container-images/issues/11) where I laid out (at the bottom) a better way then using that script to do it. If you aren't terminating SSL at Plex I don't see what the purpose of importing your cert is doing.

**Comment by onedr0p** [comment]
@acjohnson how is your experience with using those cert settings in Ple? In my tests I couldn't get it to work, so I'm curious how people were using that cert script.

**Comment by acjohnson** [comment]
All I've used is the old chart with pkcsMangler and cert-manager + ingress-nginx like this
```
  --set ingress.enabled=true \
  --set ingress.tls[0].hosts[0]="plex.example.com" \
  --set ingress.tls[0].secretName="plex-example-com-tls" \
  --set ingress.annotations."kubernetes\.io/ingress\.class"="nginx" \
  --set-string ingress.annotations."kubernetes\.io/tls-acme"="true" \
  --set ingress.annotations."cert-manager\.io/cluster-issuer"="letsencrypt-production" \
  --set ingress.annotations."nginx\.ingress\.kubernetes\.io/rewrite-target"="/" \
  --set ingress.hosts[0]="plex.example.com" \

  --set certificate.pkcsMangler.enabled=true \
  --set certificate.pkcsMangler.setPlexPreferences.customCertificateDomain="plex.example.com" \
  --set certificate.pkcsMangler.pfxPassword.value="<secret>" \
  --set certificate.pkcsMangler.certificateSecret.name="plex-example-com-tls" \
```
I'm willing to figure it out using the new chart and see if I can get it to work that way.

**Comment by onedr0p** [comment]
```
  --set certificate.pkcsMangler.enabled=true \
  --set certificate.pkcsMangler.setPlexPreferences.customCertificateDomain="plex.example.com" \
  --set certificate.pkcsMangler.pfxPassword.value="<secret>" \
  --set certificate.pkcsMangler.certificateSecret.name="plex-example-com-tls" \
```

For this part, what is it doing for you? You already have SSL terminated at nginx.

**Comment by acjohnson** [comment]
Yeah good question. I've had issues with certain frontend apps for different smart tvs/chromecast/devices that I need both https (443) and the plex native port 32400 open at the load balancer with the same TLS certs installed. I have the same issue with emby frontend apps as well.
