### ISSUE TITLE
Migrate non-common charts to common

### ISSUE THREAD

**Issue by onedr0p** [k8s-at-home/charts#718]
# Details

There's a number of charts not on common that could be migrated. Anyone is free to pick these up and convert them over.

## Charts with basic config

- [x] stable/adguard-home
- [x] stable/digitalocean-dyndns (deprecated)
- [x] stable/homebridge
- [x] stable/librespeed
- [x] stable/prometheus-nut-exporter
- [x] stable/rtorrent-flood
- [x] stable/ser2sock
- [x] stable/speedtest-prometheus (deprecated)
- [x] stable/comcast
- [x] stable/bitwardenrs (deprecated)
- [x] stable/duplicati
- [x] stable/intel-gpu-plugin
- [x] stable/modem-stats
- [x] stable/speedtest (deprecated)
- [x] stable/teslamate
- [x] stable/uptimerobot-prometheus
- [x] stable/uptimerobot (deprecated)

## Charts with advanced config

- [ ] stable/traefik-forward-auth
- [ ] stable/oauth2-proxy
- [ ] stable/powerdns
- [ ] stable/unifi

**Comment by Ornias1993** [comment]
I've ported the HPA for Bitwardenrs and traefik-forward-auth to common.
I've a common version of bitwardenrs mostly ready and will submit it to kah :)

**Comment by onedr0p** [comment]
I am going to close this issue as we have the majority of charts out of the way. The rest remaining might be difficult to migrate.

**Comment by Ornias1993** [comment]
@onedr0p We at TrueCharts use a common chart to run unifi without issues, whats the problem here exactly?

**Comment by onedr0p** [comment]
You're right, that one shouldn't be too hard.

@nicholaswilde want to give it a shot?

**Comment by Ornias1993** [comment]
Awesome :D

**Comment by nicholaswilde** [comment]
It looks like the k8s@home chart has extras, such as [mongodb](https://github.com/k8s-at-home/charts/blob/6fd1f76c34b77f1cd6df59f9538258f6ee811fd9/charts/stable/unifi/values.yaml#L247), [customCert](https://github.com/k8s-at-home/charts/blob/6fd1f76c34b77f1cd6df59f9538258f6ee811fd9/charts/stable/unifi/values.yaml#L226), and [logging](https://github.com/k8s-at-home/charts/blob/6fd1f76c34b77f1cd6df59f9538258f6ee811fd9/charts/stable/unifi/values.yaml#L236). Do we want to keep them?

**Comment by onedr0p** [comment]
I would suggest leaving the mongodb and logging stuff out. Not sure about the customcert

**Comment by Ornias1993** [comment]
customCert is just a few env-vars and a mountpoint under the hood as far as I can see. Should be relatively easy to port.
