### ISSUE TITLE
[media-common] Breaking ingress change

### ISSUE THREAD

**Issue by chris-sanders** [k8s-at-home/charts#73]
Several of my deploys are failing recently and I just dug into what's going on. It appears media-common had some updates to the ingress to meet new 1.19 requirements. That change is [here](https://github.com/k8s-at-home/charts/commit/b8ae05556163dc7756e6eee2b7310d7656f427c5).

The change bumped the Minor version from 1.1.1 to 1.2.0. This being non-backwards compatible I believe it should have bumped the major version to 2.0.0 instead.

The charts repository then had [this change](https://github.com/k8s-at-home/charts/commit/12752f4018851f99694a30f041fb389e0be5f1ca) landed which switches the media-common from "~" to "^" versioning which allows Minor and Patch instead of just Patch upgrades.

The result is that all media-common charts with the 2nd change (sonarr, radarr, organizr) have a backwards incompatible change to their values.yaml. The ingress used in those charts require that the 'paths' key have a map rather than list of paths as was previously in the chart.

It's a good change, I believe the error in this is actually the first commit which should have bumped the Major version, so that anyone using the supporting charts with ~ or ^ matching wouldn't receive a backwards incompatible change. For now I've pinned my chart directly to the release from a few days ago.

I think rolling back the 1.2.0 media-common, bumping the change to 2.0 and then bumping the umbrella charts major versions would be the correct way to version this change such that existing charts are aware this is a non-backwards compatible change and won't pull it in automatically.

**Comment by billimek** [comment]
FYI @DirtyCajunRice ^^^

**Comment by buroa** [comment]
Agreed, this change broke me when I wanted to upgrade. Now I'm using all the new formats and everything is OK again.

**Comment by onedr0p** [comment]
This should be fixed in the latest common chart, please reply if there's still issues.
