### ISSUE TITLE
[media-common] Annotations and Labels

### ISSUE THREAD

**Issue by madchr1st** [k8s-at-home/charts#74]
As far as I can tell, there is currently no possibility to add `annotations` or `labels` to the `statefulsets` or `deployments` managed by the `media-common` chart, is that correct?

Use case:
- organizing resources
- 3rd party tools that read annotations/labels (e.g. keel)

**Comment by DirtyCajunRice** [comment]
I am confused as to your goal with annotations and labels on the statefulset/deployment itself. helm create does not even have this option by default
https://github.com/helm/helm/blob/e1d4c674375e724d6cf72c91219986cc453f4c76/pkg/chartutil/create.go#L256-L259

The convention has been to add `podAnnotations` which exist here
https://github.com/k8s-at-home/charts/blob/0470f937bf080cd198b13cc60fedfda4a0468052/charts/media-common/templates/statefulset.yaml#L16-L19

Do you happen to have docs where it is currently/commonly used? More than happy to add, but complexity without necessity causes undue deviation 😄

**Comment by madchr1st** [comment]
Thanks for the follow up.

I completely agree with you:
>complexity without necessity causes undue deviation

My primary use case is Keel, which watches certain labels or annotations on deployments/satetfulsets/daemonsets (not on pods) to trigger a poll for new container tags. See here: <https://keel.sh/docs/#additional-settings>

Before switching to `media-common`, most of the helm charts I used, made use of `deploymentAnnotations`. Many of the charts in this repo still do: <https://github.com/k8s-at-home/charts/search?q=deploymentAnnotations>
