### ISSUE TITLE
[powerdns] deprecate chart

### ISSUE THREAD

**Issue by onedr0p** [k8s-at-home/charts#742]
# Details

**Helm chart name:**

powerdns

**Describe the solution you'd like:**

Deprecate chart

**Anything else you would like to add:**

Coredns is the more popular choice for a dns server in the cluster. We also really don't have any maintainers on this and it's an kind of complex helm chart to support.

@carpenike what do you think about this?

**Comment by carpenike** [comment]
I'm good with it -- might be worth doing an announcement to see if anyone would be willing to maintain it. I do believe there were people that were using it based on previous issues that were opened. But we certainly don't have many folks using it.

**Comment by turnrye** [comment]
I was actually just digging through this and came across this chart. I noticed that on https://artifacthub.io/ there aren't really any DNS server charts besides this and the upstream from @halkeye.

My interest in this chart is different from what you're mentioning @onedr0p -- I'm looking for a chart to use as a DNS recursor *outside* of the cluster. Looking at this chart, it seems like this could be a reasonable fit for my usecase. Now granted, I'm still a novice at helm and k8s in general, so if my understanding is wrong please let me know.

All that said, if someone is open to onboarding me to maintaining, I would be interested.

**Comment by carpenike** [comment]
Perfect. You're hired. :) The hours are minimal and the pay even smaller.

**Comment by onedr0p** [comment]
Thanks for the info @turnrye

> I'm looking for a chart to use as a DNS recursor outside of the cluster.

Meaning to say you have another cluster only managing DNS?

**Comment by halkeye** [comment]
for the record, i'm using my chart to run DNS for my house, it goes blocky => powerdns-recursor=> powerdns I just have a ServiceType=LoadBalancer on my blocky (Actually i have them on all 3, but I realize now I just need blocky exposed)

**Comment by turnrye** [comment]
> for the record, i'm using my chart to run DNS for my house, it goes blocky => powerdns-recursor=> powerdns I just have a ServiceType=LoadBalancer on my blocky (Actually i have them on all 3, but I realize now I just need blocky exposed)

Cool, thank you. That verifies what I'm looking to do. Just making sure I understand correctly -- you have two deployments of your same pdns chart, just configured differently (one authoritative, one recursive). Right?

**Comment by halkeye** [comment]
Looks like I never published recursor - https://github.com/halkeye/helmfile/blob/master/namespaces/dns/helmfile.yaml
I think i was just being lazy. If i get a minute I'll convert it to a published chart.

**Comment by turnrye** [comment]
@halkeye that's most appreciated. I'm realizing as I deep-dive on the powerdns chart here that it only grabs powerdns, not pdns_recursor. That means that this chart actually does not suit my initial use case. If you do end up publishing yours LMK and I'll happily be a user for recursion.

But just like @halkeye , I also run an authoritative DNS server for serving DNS records to the internet at large. Today I do that on a VM, and this seems like an opportunity to migrate and benefit from some of the HA that k8s can offer. So, sign me up to maintain.

**Comment by carpenike** [comment]
@turnrye -- yup this chart was left intentionally lean so as to accommodate more use cases that may not need the various plugins. The original goal was to enable other sub-roles that could be enabled but were not baked into the base deployment/ requirement.

**Comment by onedr0p** [comment]
I'll go ahead and close this issue, thanks all for your comments. We will keep it around!
