### ISSUE TITLE
New Chart Requests

### ISSUE THREAD

**Issue by DirtyCajunRice** [k8s-at-home/charts#784]
New common-based chart requests

| created | app | alternate | 
| --- | --- | --- |
| ✔️ | [bookstack](https://www.bookstackapp.com/) | [nicholaswilde/bookstack](https://github.com/nicholaswilde/helm-charts/tree/main/charts/bookstack) |
| ✔️ | [thelounge](https://github.com/thelounge/thelounge) | [halkeye-helm-charts/thelounge-chart](https://github.com/halkeye-helm-charts/thelounge-chart) |
| ✔️ | [haste-server](https://github.com/seejohnrun/haste-server) | [nicholaswilde/haste](https://github.com/nicholaswilde/helm-charts/tree/main/charts/haste) |

Putting it up as a note to self really... if someone gets to something first... great!

**Comment by nicholaswilde** [comment]
I think we can move the bookstack and haste Docker images over too the `container-images` repo as well.

**Comment by DirtyCajunRice** [comment]
> I think we can move the haste Docker image over too the `container-images` repo as well.

Nice!. Sounds good.

**Comment by nicholaswilde** [comment]
@DirtyCajunRice I'll take care of moving the haste docker image to container-images.

**Comment by nicholaswilde** [comment]
@DirtyCajunRice haste image has been published. https://github.com/orgs/k8s-at-home/packages/container/package/haste

**Comment by rwaltr** [comment]
PR #794 created for `thelounge`

**Comment by rwaltr** [comment]
Created #800 for `haste-server`

**Comment by onedr0p** [comment]
only one left is bookstack 🎉

**Comment by nicholaswilde** [comment]
For bookstack, do we want to use the LSIO image or create our own?

**Comment by onedr0p** [comment]
We could use LSIO for the time being.

**Comment by nicholaswilde** [comment]
I can take bookstack.

**Comment by nicholaswilde** [comment]
Created #817 for `bookstack`.

**Comment by nicholaswilde** [comment]
`bookstack` has been released.

**Comment by onedr0p** [comment]
Issue closed! Good work everyone

**Comment by DirtyCajunRice** [comment]
Yall beasts
