### ISSUE TITLE
Add Speedtest-Exporter or replace the existent

### ISSUE THREAD

**Issue by MiguelNdeCarvalho** [k8s-at-home/charts#793]
# Details

**Helm chart name:**

Speedtest-Exporter

**Describe the solution you'd like:**

Would be possible to add https://github.com/MiguelNdeCarvalho/speedtest-exporter/ ?

Thanks,
MiguelNdeCarvalho

**Comment by onedr0p** [comment]
I believe this is possible, I will change the chart over to the common library too.

**Comment by MiguelNdeCarvalho** [comment]
Nice thanks
