### ISSUE TITLE
Deprecate uptimerobot in favor of uptime-prometheus

### ISSUE THREAD

**Issue by onedr0p** [k8s-at-home/charts#827]
# Details

As we did for the speedtest chart, deprecate this one in favor of the prometheus exporter.

@billimek do you have any issue with this?

**Comment by billimek** [comment]
@onedr0p I suggest against this.  There is a pretty significant gap (IMO) with the uptimerobot-prometheus chart.  It leverages  the [uptimerobot_exporter](https://github.com/lekpamartin/uptimerobot_exporter) solution and that will never capture an outage that is resolved within the prometheus polling interval.

Basically, the uptimerobot_exporter works by checking the uptime robot current state at each prometheus polling interval.  Consider the following:

* t0: outage occurs
* t1: outage resolves
* t2: `uptimerobot_exporter` polls current state

Using this approach we will never have a record of the outage that occurred which diminishes the value proposition of extracting data from uptimerobot to track outages.

See [this issue](https://github.com/lekpamartin/uptimerobot_exporter/issues/5) for some details.

**Comment by onedr0p** [comment]
No problem, I didn't the the difference between the two charts really. Thanks for filling me in 🤠
