### ISSUE TITLE
qbittorrent fails to startup complaining about /config/qBittorrent/BT_backup

### ISSUE THREAD

**Issue by halkeye** [k8s-at-home/charts#828]
# Details

**Helm chart name and version:**

qbittorrent   qbittorrent-10.0.0      v4.3.4.1

**Container name and tag:**

ghcr.io/k8s-at-home/qbittorrent:v4.3.4.1

**What steps did you take and what happened:**

node restarted, so container restarted

**Relevant Helm values:**

??? I would guess having persistence enabled

**What did you expect to happen:**

Startup works

**Anything else you would like to add:**

kubectl logs -n media qbittorrent-64877fcd8-x8lbk -p
Cannot write to torrent resume folder: "/config/qBittorrent/BT_backup"% 

~I suspect its related to https://github.com/qbittorrent/qBittorrent/issues/9531, but after deleting session.lock i'm getting~
looks like it was initialiiy running as 1000 (maybe because of PUID env variable) but now its 568

**Comment by onedr0p** [comment]
Please see our docs on permissions with using the kah images:

https://docs.k8s-at-home.com/our-container-images/permissions/

**Comment by halkeye** [comment]
> Not sure why or how on your end the chart upgraded to a breaking change without any intervention from you.

helm charts always pull the latest version unless you pin a version

Nothing was mentioned about changing uid in https://github.com/k8s-at-home/charts/blob/master/charts/stable/qbittorrent/README_CHANGELOG.md.gotmpl and your not using the artifacthub changelog annotations. So to the end user is a very shocking breaking change.

**Comment by onedr0p** [comment]
> helm charts always pull the latest version unless you pin a version

This is one thing I find annoying about helm since changes are breaking `--version` should be a required flag :/

> Nothing was mentioned about changing uid in https://github.com/k8s-at-home/charts/blob/master/charts/stable/qbittorrent/README_CHANGELOG.md.gotmpl and your not using the artifacthub changelog annotations. So to the end user is a very shocking breaking change.

I should have documented that in the readme changelogs :(
