### ISSUE TITLE
[Bitwarden_rs] Upstream name change

### ISSUE THREAD

**Issue by rwaltr** [k8s-at-home/charts#835]
# Details

**Helm chart name and version:**

Bitwarden_RS upstream is changing their name to [Vaultwarden](https://github.com/dani-garcia/vaultwarden/commit/34ea10475d316ccb2ca4cd2cac67b61c4cdfb62a)

**Container name and tag:**

bitwarden_rs and Vaultwarden

**Relevant Helm values:**

Image and Tags

**What did you expect to happen:**

We need to change our tags and chart name once Vaultwarden's changes reach the registrars

**Comment by rwaltr** [comment]
I'm workiong on a PR

**Comment by CuBiC3D** [comment]
Would be a good chance to migrate to common. @DirtyCajunRice wanted to convert it :D any progress?

**Comment by rwaltr** [comment]
Only basic templates atm. still need to do testing
https://github.com/rwaltr/charts/tree/vaultwarden
It appears that at least these versions of vaultwarden have all their items config thru ENV
