### ISSUE TITLE
[Charts Release] Startup Failure

### ISSUE THREAD

**Issue by nicholaswilde** [k8s-at-home/charts#868]
# Details

**Helm chart name and version:**

Charts Release

**Container name and tag:**

- [syncthing ](https://github.com/k8s-at-home/charts/actions/runs/803142393) 1.1.2 chart release ci seems to have a startup failure.
- This failure also seems to be there for subsequent chart releases.

**What steps did you take and what happened:**

- Closed and merged pull request #847
 
**Relevant Helm values:**

- N/A

**What did you expect to happen:**

- Chart to be reelased.

**Anything else you would like to add:**

**Additional Information:**

**Comment by bjw-s** [comment]
That is super weird... According to GitHub there were no jobs in the CI, but there should have been... I'll try to debug this later today. Thanks for reporting!

**Comment by bjw-s** [comment]
I messed something up when adding the workflow concurrency (I left a `needs` in he main job even though that pre-release job was removed). Should be fixed now, and the missing releases should be added now too. Sorry for the inconvenience!

**Comment by nicholaswilde** [comment]
No worries. Thanks for fixing it!
