### ISSUE TITLE
[changelogs] Version headings not showing on artifacthub.io

### ISSUE THREAD

**Issue by nicholaswilde** [k8s-at-home/charts#883]
# Details

**Helm chart name and version:** prowlarr

**Container name and tag:** N/A

**What steps did you take and what happened:**

- Updated `README_CHANGELOG.md.gotmpl` with `### [2.3.2]` heading.
- Ran `task chart:helm-docs CHART=prowlarr CHART_TYPE=stable`
- Pushed pr commit and release by team.
- [artifacthub.io](https://artifacthub.io/packages/helm/k8s-at-home/prowlarr#changelog) missing `### [2.3.2]` and `### [1.0.0]` headings but has the `Added`, `Changed`, and `Removed` headings.
- [Github page](https://github.com/k8s-at-home/charts/tree/master/charts/stable/prowlarr) shows the headings.

**Relevant Helm values:** N/A

**What did you expect to happen:**

- prowlarr to show on artifacthub.io with `### [2.3.2]` and `### [1.0.0]` headings.

**Anything else you would like to add:**

It seems that artifacthub.io doesn't recognize headings that have links. I don't know if we need to do anything about this or if we should open a ticket on artifacthub.io's repo. We can also remove the header links from the `README_CHANGELOG.md.gotmpl` file.

```diff
+### 1.0.0
-### [1.0.0]
```

**Additional Information:**

**Comment by tegioz** [comment]
Hi @nicholaswilde 

@cynthia-sg [has fixed this issue](https://github.com/artifacthub/hub/commit/3eaea80ff070d2febe4327949cd8c3faf99f071b), we'll deploy it tomorrow.

**Comment by tegioz** [comment]
Deployed! Please let us know if you find any other issue. Thanks!

**Comment by nicholaswilde** [comment]
> Deployed! Please let us know if you find any other issue. Thanks!

Thanks for fixing this! There doesn't seem to be any issues that I can see.
