### ISSUE TITLE
External Domain

### ISSUE THREAD

**Issue by plainlystated** [k8s-at-home/charts#9]
I'm probably missing something obvious, but I don't see a way to specify the public-facing domain for callbacks from third parties.  I do have `ingress.hosts` set, but when I add Plex as a vendor, that third party site tries to redirect me back to `https://<local_ip>:8123/auth/plex/<etc>`.  If I swap out the `local_ip:8123` with the proper domain, I can continue the auth flow.

**Comment by onedr0p** [comment]
Closing this issue, looks like a question that was answered
