### ISSUE TITLE
[zwave2mqtt] add probes

### ISSUE THREAD

**Issue by onedr0p** [k8s-at-home/charts#91]
Currently we only check the root path, maybe there is some improvements here:

https://github.com/OpenZWave/Zwave2Mqtt#health-check-endpoints

**Comment by bjw-s** [comment]
This is something we could/need to add to the `common` library. Currently we only implement `tcpSocket` probes, but we should also add support for `httpGet` and `exec` types.

**Comment by onedr0p** [comment]
I like this idea :)

**Comment by bjw-s** [comment]
Should be possible once #316 gets merged in 👍

**Comment by bjw-s** [comment]
Now that #316 has been merged, we can look in to how we should implement these endpoints
