### ISSUE TITLE
[frigate] - relocate frigate to new home

### ISSUE THREAD

**Issue by billimek** [k8s-at-home/charts#92]
The author of Frigate, @blakeblackshear is now hosting a [charts repo](https://github.com/blakeblackshear/blakeshome-charts) for his charts, and we should 'move' frigate to the new home.  This issue is to handle that process.

See also https://github.com/blakeblackshear/frigate/issues/156

**Comment by billimek** [comment]
The new repo is ready for this to move: https://github.com/blakeblackshear/blakeshome-charts

**Comment by onedr0p** [comment]
I think he is waiting for our help with this, however it doesn't look like anything is in that repo, I cannot fork it nor open a PR.

**Comment by blakeblackshear** [comment]
Helm chart is still on my todo list. See the version I am using here: https://github.com/blakeblackshear/billimek-charts/tree/master/charts/frigate

**Comment by onedr0p** [comment]
@blakeblackshear looks great! Let us know if you need any help getting it moved over to your charts repo and wired up with GitHub actions.

**Comment by billimek** [comment]
not stale

**Comment by bjw-s** [comment]
Now that the new Helm repo is up we can deprecate the chart in our repo. I've added a PR for this in #528, based on this approach: https://helm.sh/docs/topics/charts/#deprecating-charts.
