### ISSUE TITLE
Add support for RadarrSync

### ISSUE THREAD

**Issue by billtomturner** [k8s-at-home/charts#925]
# Details

**Helm chart name:**

radarr

**Describe the solution you'd like:**

Add support for [RadarrSync](https://github.com/Sperryfreak01/RadarrSync) as a `CronJob` to synchronize multiple copies of Radarr. This is a common solution to retaining 4K and 3D content separate from standard HD content.

**Anything else you would like to add:**

I have a PR in progress for this change, and will be testing it soon before submitting. Happy to explore other options though, if the maintainers would prefer.

**Additional Information:**

**Comment by onedr0p** [comment]
Doesn't radarr have this feature built into it? You can add a Import list from another radarr instance.

**Comment by billtomturner** [comment]
Ah, I hadn't tried that. I'll make sure it meets my needs, and close this if it does.

**Comment by onedr0p** [comment]
Closing this issue as it is supported natively in the application.
