### ISSUE TITLE
Add support for setting hostAlias in the oauth2-proxy chart

### ISSUE THREAD

**Issue by dadacom379** [k8s-at-home/charts#932]
# Details

On premise installation will need to be able to set **hostAlias** to the pod. Using  the helm chart 5.0.5 I was able to add the config to pod.
![image](https://user-images.githubusercontent.com/17455054/120691727-d1339080-c474-11eb-85be-31cea62bb6d1.png)

In my example I have hardcoded the value for the **hostAlias** section but It will be more interesting to be able to set them from the values.yaml

**Comment by dadacom379** [comment]
Any news

**Comment by bjw-s** [comment]
Sorry for the lack of updates on this one, as we have been busy with other things. It might be a while before we can get to this, but if you can submit a PR we will definitely make some time to review it and get it merged.

**Comment by onedr0p** [comment]
We no longer provide this chart as there is an official upstream one.
