### ISSUE TITLE
Stable charts need brief documentation for charts

### ISSUE THREAD

**Issue by hyperbolic2346** [k8s-at-home/charts#962]
The [main stable charts page](https://github.com/k8s-at-home/charts/tree/master/charts/stable) has grown to be quite large with names that I don't recognize. This is a great thing and I can click on each chart and read a summary of what these things do, but it would be very helpful to have a README.md in that directory that lists the charts and a very quick blurb about what they are. Something like:
```
- plex - A media server for your home
- monica - A personal assistant to help keep track of your personal connections
```

**Comment by rwaltr** [comment]
since all our docs are gened and not hand done, We might be able to get away with reading line 4 of every doc,

Otherwise we could use yq to get description and name from each subfolder

**Comment by bjw-s** [comment]
While `yq` adds "some" overhead, I'd still prefer that over relying on line 4 always being the correct one 😅
